### ISSUE TITLE
Gmask with < > doesnt work

### ISSUE THREAD

**Issue by Thund3rst0rm89** [IntellectualSites/FastAsyncWorldEdit-1.13#101]
i only want to place something over sand. if i use the regular world edit it works with /gmask >sand. But in Fawe it looks like this
https://www.bilder-upload.eu/upload/b488da-1554574116.png

Placed everywhere but not on the top of sand. I think the < > doesn't work

We use Paperspigot 1.13.2, and Fawe #147

**Comment by SirYwell** [comment]
#61 malfunction of that was already reported
