### ISSUE TITLE
//move duplicates entities 

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/FastAsyncWorldEdit-1.13#104]
# Bug report for FastAsyncWorldEdit 1.13.x
**Debug paste link**:
https://incendo.org/paste/view/017531b29f4b415aadd5a5169f1b0af2
-> breaking build `#15`

**Description of the problem:**
Moving a region containing entities (such as Armorstands, item frames or minecarts) duplicates them.

**How to replicate**:
- Select a region like in the gif below
- `//move`
- View the result https://gyazo.com/2f7ab022e99d9ac2a15a6d9f39519a85

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
can't replicate. Assumed fixed.
