### ISSUE TITLE
FAVs overlay brush not working

### ISSUE THREAD

**Issue by 0xC1A551C** [IntellectualSites/FastAsyncWorldEdit-1.13#108]
**Debug paste link**:
https://incendo.org/paste/view/a32b0e5d8f08411f96f216989cd4b04d
**Description of the problem:**
When using the voxelsniper FAVs overlay brush it does nothing. Sometimes changes a few random blocks, but overall does nothing when it should overlay a sphere of whatever block is selected.

**How to replicate**:
/b over all
/v grass_block
/b 5

Sets the overlay to all, changes the block to grass with a radius of 5.

Paper 1.13.2 build 600 latest 1.13 FAWE and FAVs

**Comment by Tsoccerguy3** [comment]
Tested with latest commit , confirmed Voxel overlay is not working

**Comment by N0tMyFaultOG** [comment]
Duplicate of #100
