### ISSUE TITLE
FAWE doesnt log FAVS actions in history.

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#111]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:

https://incendo.org/paste/view/a5cb27f0ff33467a9298be9f59853b9f
**Description of the problem:**

Unable to undo edits made by voxelsniper.

Voxel apparently doesnt hook(?) into FAWE's history

**How to replicate**:
 Do something with voxelsniper that changes blocks and then try to undo.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Can you try updating Fawe/Favs with the latest breaking build ([get it here](https://incendo.org/download))? Maybe give your paper build an update as well, you are almost 100 versions behind. I tested it with the latest ones and was unable to reproduce your issue.

**Comment by RealmportalMC** [comment]
Still a problem :/

**Comment by boy0001** [comment]
can't replicate with latest FAWE breaking

**Comment by RealmportalMC** [comment]
I still can :/
happens every time with the snipe brush line brush, disc brush, ball brush (which are what ive tested
