### ISSUE TITLE
disallowed-blocks does not work

### ISSUE THREAD

**Issue by Drc-DEV** [IntellectualSites/FastAsyncWorldEdit-1.13#115]
**Debug paste link**:
https://incendo.org/paste/view/b288fa012494466db8af167ecbe97f67

**Description of the problem:**
disallowed-blocks in config-legacy.yml does not work
I tested both:
    disallowed-blocks:
    - OAK_SAPLING
and
    disallowed-blocks: [6, 7, 14, 15, 16, 26, 27, 28, 29, 39, 31, 32, 33, 34, 36, 37, 38, 39, 40, 46, 50, 51, 54, 56, 59, 69, 73, 74, 75, 76, 77, 81, 83, 130, 146, 154, 119, 200, 209]
Both did not work. I restarted after making any config change.

**Comment by boy0001** [comment]
fixed in 24590199c8c349ae488f57dc96e7e14e6a5416be
