### ISSUE TITLE
NPE on /br apply

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#119]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:

https://incendo.org/paste/view/6bfb2ad083184b2c89b710638f4156f4
**Description of the problem**
Null Pointer when using /br apply sphere size set material

https://pastebin.com/2MFPtPT2

**How to replicate**:

type /br apply sphere size set material

size and material doesnt seem to affect the outcome

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Can't replicate, assumed fixed.
