### ISSUE TITLE
Being able/not able to bind brushes to your hand

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/FastAsyncWorldEdit-1.13#123]
# Bug report for FastAsyncWorldEdit 1.13.x
**Debug paste link**:
https://incendo.org/paste/view/4837e65fe2f2468f818afdd05602d539

**Description of the problem:**
Binding brushes works/doesn't work

**How to replicate**:
Hold no item in your hand and try to set a brush, eg `//br sphere bedrock 7`
https://pastebin.com/c7TdZ0TN
I remember that this didn't work for some time, but now you can bind brushes to your fist again but it simply doesn't work even if it tells you that you bound the brush correctly. I'm not sure which behaviour is supposed to work. 

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Was fixed
