### ISSUE TITLE
Lightning commands interfering with Paper timings

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/FastAsyncWorldEdit-1.13#127]
# Bug report for FastAsyncWorldEdit 1.13.x
**Debug paste link**:
https://incendo.org/paste/view/5040c7f1741b41538facd169756de057
Paper 620 and Fawe breaking build `#73`

**Description of the problem:**
`//setskylight` and `//setblocklight` seem to work, but have some issues with Paper
**How to replicate**:
Use the commands, check the console, voilà
Check the debugpaste for the stacktrace.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Moving stacktrace to pastebin https://pastebin.com/ev5EvUha

**Comment by Tsoccerguy3** [comment]
related to old issue , posted here
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/16#issue-399888498

**Comment by xion87** [comment]
for me setblocklight it crash the server https://gist.github.com/xion87/1abecafae785363deb933cfbcc8df56a
