### ISSUE TITLE
//undo doesnt undo all blocks

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#128]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
https://incendo.org/paste/view/a7ec36bf1df1407580bb16bb254c9320

**Description of the problem:**

![2019-04-16_18 33 03](https://user-images.githubusercontent.com/22693741/56250781-66495480-6076-11e9-9339-6a3fa85f77e6.png)
(this affects more than the brushes probably)
**How to replicate**:
 do /br height 50 
then use the brush twice and attempt to //undo

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by Drc-DEV** [comment]
Just happened to me. This affects also //copy and //paste, especially with big clipboards.

**Comment by Tsoccerguy3** [comment]
Recent compile and test . As of commit e9048c3913f8570eb2162f8f0153011006071e1d , //undo is leaving some blocks behind . Confirmed
