### ISSUE TITLE
Copy / Paste

### ISSUE THREAD

**Issue by PapiCapi** [IntellectualSites/FastAsyncWorldEdit-1.13#129]
**Debug paste link**:
https://incendo.org/paste/view/a7db6be44db44d6a8f444d0f70f9b4e9

**Description of the problem:**
If we copy a selection where there are stairs (and maybe a lot of other blocks) , they are not pasted. 

**How to replicate**:
Copy and paste a selection where there are stairs.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Give fawe an update

**Comment by PapiCapi** [comment]
I took the last build from here : https://ci.athion.net/job/FastAsyncWorldEdit-1.13/ . Isn't it the last update ?

**Comment by N0tMyFaultOG** [comment]
No, use the builds from here: https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/
They contain various fixes and are closer behind upstream

**Comment by PapiCapi** [comment]
Ok, thanks a lot !
Sorry for this useless issue

**Comment by N0tMyFaultOG** [comment]
Dw, it's fine. If you encounter a new one, feel free to open a new ticket :P
