### ISSUE TITLE
Bug when setting or replacing glass panes with FAWE

### ISSUE THREAD

**Issue by MartynBlackburn** [IntellectualSites/FastAsyncWorldEdit-1.13#13]
XX
 error: java.IOException: code 503.

**Description of the problem:**

When using FAWE to set or replace glass panes (of any colour) they either don't set properely and resemble "sticks" of glass and do not attack to any surrounding blocks, or do not change at all when replacing with a different block.

**How to replicate**:
XX

//set black_stained_glass_pane (renders in glass "sticks" and never in panes)
//replace black_stained_glass_pane air (no change, but with console message: "no blocks affected")
//replace black_stained_glass_pane 0 (no change, but with console message: "no blocks affected")
//set 0 (deletes panes as expected)

Hyperlink to server log report from within game during when the commands were carried out: https://paste.ofcode.org/MSvHTuWppWdQ8d76MhS53e

**Comment by AeSix** [comment]
This is still an issue with FAWE-NVS 165
https://incendo.org/paste/view/8f1a5635577e447b9aa49fdeab02bc25

The issue is probably related to the server now handling block connections. 
Here's a post explaining that pretty clearly:
https://github.com/ViaVersion/ViaVersion/issues/856

**Comment by Sauilitired** [comment]
Superseded by https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/18.
