### ISSUE TITLE
Pasting rotated Clipboard results in missing signs/chests

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit-1.13#132]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**: not included bc not working and for privacy reasons

**Description of the problem:**

When pasting a rotated clipboard, chests and signs (and probably other stuff with nbt-data) isn't pasted

**How to replicate**:

Copy a region with signs/chests whatever
//rotate 90
//paste

**Checklist**:

- [ ] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/) - latest version
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by baticag** [comment]
Also having the same problem

**Comment by Tsoccerguy3** [comment]
Control group . //copy then //rotate 90  .  I tested all types of chests with a mounted sign on each . each chest type had red_wool , egg , player head . 

![2019-06-05_08 40 15](https://user-images.githubusercontent.com/22108822/58958497-05362700-8771-11e9-9b4b-48b9ab85a840.png)

**Comment by Tsoccerguy3** [comment]
First test , Enderchest . paste results in invisible enderchest with invisible sign , as can be seen by the outline of the sign . then opening the enderchest results in the enderchest becoming visible and  contents are intact .

![2019-06-05_08 45 39](https://user-images.githubusercontent.com/22108822/58959323-d1f49780-8772-11e9-9a5b-43315c655691.png)
![2019-06-05_08 45 46](https://user-images.githubusercontent.com/22108822/58959324-d28d2e00-8772-11e9-946e-38dc698ee342.png)
![2019-06-05_08 46 00](https://user-images.githubusercontent.com/22108822/58959325-d28d2e00-8772-11e9-8463-ff4214aedd0f.png)

**Comment by Tsoccerguy3** [comment]
Second test , minecart chest with mounted sign and Iteme_frame with Item . Minecart chest is visible on //paste and contents are intact . sign is invisible and Item_frame and Item break away from block .
![2019-06-05_08 46 20](https://user-images.githubusercontent.com/22108822/58959643-8393c880-8773-11e9-95cf-2de0b2f39b6c.png)
![2019-06-05_08 46 23](https://user-images.githubusercontent.com/22108822/58959644-8393c880-8773-11e9-8d57-6fc4d98f4095.png)

**Comment by Tsoccerguy3** [comment]
Third Test , single and double , regular Chests and Trapped chests . All chests and signs are invisible on //paste . The chests , 
![2019-06-05_08 46 41](https://user-images.githubusercontent.com/22108822/58959957-2a786480-8774-11e9-87b5-35907e684b6f.png)
![2019-06-05_08 46 54](https://user-images.githubusercontent.com/22108822/58959963-2c422800-8774-11e9-95a0-2d05ee17dc61.png)
![2019-06-05_08 47 52](https://user-images.githubusercontent.com/22108822/58959965-2c422800-8774-11e9-8ef3-f8d31cbeb969.png)


become visible on opening , contents are missing .

**Comment by Tsoccerguy3** [comment]
Tested FAWE breaking 1.14 , still broken with 1 extra artefact , chests wont copy and paste . nothing happens .

**Comment by TheoRetisch1** [comment]
I have the same problems:
Boxes and signs don't rotate or flip. If you dare, they become invisible and empty.
Itemframes and pictures are not copied at all.
This is a disaster while building, it would be mega cool if you could get a grip on it :)

The test was done using a newly generated config with FAWE version 176 and a newly generated DUMMY file.
FAWE 1.13.176
Paper 1.13.2 - 641
