### ISSUE TITLE
ClassNotFoundException AsyncTabCompleteEvent

### ISSUE THREAD

**Issue by andfont** [IntellectualSites/FastAsyncWorldEdit-1.13#133]
Versions
FastAsyncWorldEdit version 1.13-breaking FastAsyncWorldEdit-bukkit-1.13.99
worldguard-legacy-7.0.0-beta-02 - fawe
MC version 1.13.2
ALL LOG ERROR:
https://pastebin.com/Y8kuG2HC
CONCRETE ERROR:
```
[11:09:49 INFO]: (FAWE) Plugin 'WorldGuard' found. Using it now.
[11:09:49 WARN]: java.lang.ClassNotFoundException: com.destroystokyo.paper.event.server.AsyncTabCompleteEvent
[11:09:49 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[11:09:49 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136)
[11:09:49 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:82)
[11:09:49 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[11:09:49 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[11:09:49 WARN]:        at java.lang.Class.forName0(Native Method)
[11:09:49 WARN]:        at java.lang.Class.forName(Class.java:264)
[11:09:49 WARN]:        at com.boydti.fawe.bukkit.FaweBukkit.lambda$new$0(FaweBukkit.java:138)
[11:09:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[11:09:49 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[11:09:49 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[11:09:49 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[11:09:49 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[11:09:49 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[11:09:49 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by N0tMyFaultOG** [comment]
You can either ignore the it or switch to paper like suggested

**Comment by andfont** [comment]
I do not understand the answer, can you arrange that the error does not come out please? or how to change it? so that the message does not come out thanks!

**Comment by SirYwell** [comment]
This error message has no impact on functionality. Probably someone will add a check to prevent it some day, but it's not a high priority thing.

**Comment by IronApollo** [comment]
Would you provide additional context? Does this error occur solely on startup, or does it occur every time someone types, or every time a command is being typed?

I believe it should only occur once at startup as a result of FAWE determining the proper event to listen to while parsing tab completions.

**Comment by SirYwell** [comment]
Since I'm bound to spigot atm, I have that too, and as you said, it only occurs once at startup for me.

**Comment by andfont** [comment]
this error occurs only with the "breaking" but it does not happen with the 147, at the moment I only see at the beginning but it is possible that at some point it will have consequences! so when you can fix the error thank you!

**Comment by boy0001** [comment]
No consequences, it's just debug.

**Comment by MattBDev** [comment]
@andfont if you use a Paper server instead of Spigot the error won't print out. Paper is recommended over Spigot.

**Comment by andfont** [comment]
? as? we always use spigot, do not know paper server? we will never use a platform that has less support than spigot, please when it is possible to fix the error and that it does not come out like version 147 of fastwolrd edit thanks.

**Comment by MattBDev** [comment]
Paper doesn't have less support than spigot. We recommend it because if you use it you are likely to run into less bugs and have better performance.
It may print out a message but it doesn't hurt the server in any way.
Please check paper out at the link I'm providing:
https://papermc.io/

**Comment by andfont** [comment]
we have been looking at it and it has less support, less forums, it does not have forums and poise, the web is simpler and it does not have tools like the builtools etc. the compilation is much bigger! 47 megabytes and spigot is much more DEPURED and only occupies 27 megabytes, with the paper we have left more errors than other PLUGINS! a disaster! We will never use paper, please fix the error like this in the 147 of fastwolrdedit, thanks!

**Comment by sweepyoface** [comment]
That's a copypasta, right guys?

**Comment by Draycia** [comment]
https://cdn.discordapp.com/emojis/532619440563683328.png?v=1

**Comment by Draycia** [comment]
![peepoGiga](https://user-images.githubusercontent.com/15833072/56948220-4db05400-6ae4-11e9-84f4-2b0e366fa27d.png)

**Comment by 0-x-2-2** [comment]
>less support

Uhh wym: https://github.com/PaperMC/Paper/issues/

>less forums

Uhh wym: https://papermc.io/forums/

>it does not have tools like the builtools

Why do you need buildtools

>the compilation is much bigger! 47 megabytes and spigot is much more DEPURED and only occupies 27 megabytes

If you are using buildtools spigot is gonna use way more space. if you really care about space on your server you can use the "paperclip.patchonly" system property with the paper patcher and just use the jar it generates on your server.

>with the paper we have left more errors than other PLUGINS

What plugins? Most plugins that I have tested work perfectly fine on paper and the ones that did not work just disabled themselves if paper is detected but work fine after the check was removed.

>please fix the error like this in the 147 of fastwolrdedit, thanks!

https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/133#issuecomment-487690443

**Comment by dordsor21** [comment]
If you're worried about 20MB of space then stop running your server on an array of floppy disks. Also, as you've been told multiple times... it's not an error that affects.... anything...?

**Comment by andfont** [comment]
It is not solved! why do you close it? if it gives errors the paper and many! as you notice that you do not use servers! It has no better spigot errors! you can not force other people to use the server! very bad that you close the case when it is not solved! although it is not very important very badly!

**Comment by dordsor21** [comment]
Did you even look at the commit! As you notice that you do not use GitHub! It has no more spigot errors!

**Comment by andfont** [comment]
???? close the case without being resolved I tried to use a paper that is much worse in functionality timings paste etc etc many things are worse! very badly you the spigot works much better in many things and I DO NOT GIVE ANY ERROR. very bad you!

**Comment by dordsor21** [comment]
What the fuck are you on about... I made a commit that stopped the error being pasted? We just advise you to use paper because the only thing it's worse at is being less configurable.

**Comment by dordsor21** [comment]
See e2c9454 "Don't print stack trace, print another few lines of debug for using paper [instead]"

**Comment by MattBDev** [comment]
@andfont You clearly never tried to use paper and are just being stubborn. Paper is more reliable than Spigot and has more features which FAWE relies on for functionality. Without paper, FAWE could break more frequently.

**Comment by andfont** [comment]
READ UP PLEASE !! if I have tried it and I have told you that it gives MANY errors in many plugins that we need, but you do not want to listen to people trying to use paper! It will not be my case to continue like that! You yourselves can not justify an error so that people change to paper that is incredible! but it is that it gives errors then I pass the LOG to you when I have a moment. :(

**Comment by MattBDev** [comment]
I already told you to continue this discussion on discord. The error is gone and replaced with a recommendation for paper message. I am now locking this issue
