### ISSUE TITLE
(BUG) FAWE WorldGuard Compatibility

### ISSUE THREAD

**Issue by johnsoncui02** [IntellectualSites/FastAsyncWorldEdit-1.13#135]
# Bug report for FastAsyncWorldEdit 1.13.2

Paper Build-597: Version 1.13.2

Console Error: https://pastebin.com/raw/xrz53Zk1

**Description of the problem:**
FAWE would make WorldGuard 7.0.0 (BETA 3) not loadable when FAWE is installed inside. It works with world edit however. Not sure if this is the actual console error but it's for certain that it prevents worldguard from loading when FAWE is present.

**How to replicate**:
Plug and play.

**Comment by N0tMyFaultOG** [comment]
Please follow the format given, it seems to work fine for me.
