### ISSUE TITLE
fawe debug paste results in HTTPS 503 response

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#14]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:

N/A

Using the version Ironapollo sent me to test the vector update

**Description of the problem:**

/fawe debugpaste results in
 java.io.IOException: Server returned HTTP Response code 503 for URL: https://hastebin.com/documents 

**How to replicate**:

type /fawe debug paste
it will take a minute, But returns 503 response code

**Checklist**:

- [n/a] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

Mostly relavent due to my inability to send FAWE debug paste for other issues

all config settings are on default.

**Comment by N0tMyFaultOG** [comment]
The issue belongs to hastebin, check the PR's we are working on our custom solution.

**Comment by RealmportalMC** [comment]
Im aware it belongs to hastebin, the trouble is IronApollos vector update im having some troubles with and im unable to send FAWE debug pastes with

**Comment by N0tMyFaultOG** [comment]
The update is not meant to be used aside for testing purposes, he posted an explanation how you can participate in testing and report issues properly.

**Comment by RealmportalMC** [comment]
thats what im doing. where do i post the issues then?

**Comment by N0tMyFaultOG** [comment]
Post the errors you get on pastebin and link them here with a proper way to reproduce them, otherwise we cannot help with them

**Comment by RealmportalMC** [comment]
Ok. i should open a new issue to keep things cleaner, just close this one

**Comment by N0tMyFaultOG** [comment]
Good idea, mention him on issues so we know that those are for him and his releases :P
