### ISSUE TITLE
Leaves (block) not replacing properly

### ISSUE THREAD

**Issue by BetTD** [IntellectualSites/FastAsyncWorldEdit-1.13#140]
# Bug report for FastAsyncWorldEdit 1.13.2
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit 1.13-19.5.4-2be8d87-106

**[REQUIRED] Spigot/Paper Version Number:** 
[16:21:53 INFO]: This server is running Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[16:21:53 INFO]: Previous version: git-Paper-622 (MC: 1.13.2)
[16:21:53 INFO]: Checking version, please wait...
[16:21:54 INFO]: You are running the latest version

**Links to config.yml and config-legacy.yml file:** 
https://filehost.5stars-modding.ml/BetTD/FAWE/ (both files are listed there)

**[REQUIRED] Description of the problem:**
For some reason FAWE loves to not replace and/or set a gmask on any type of leaves. If I do //replacenear 80 oak_leaves air it will just show 0 blocks affected. I think it's because of the distance parameter BS.

**Plugins being used on the server:**
[16:22:56 INFO]: Plugins (56): AAC, AreaShop, ArmorStandTools, BanManager*, BKCommonLib, BlocksHub, BungeeGuard, ChestCommands, Citizens, CleanroomGenerator*, ClearLag*, ColoredSigns*, CoreProtect, dynmap*, Elevator*, Elevators*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, Factions,
GlobalExecute*, HolographicDisplays, HolographicScoreboard*, iDisguise, ImageMaps*, Jobs, LightCleaner, LuckPerms, LWC, MassiveCore, Multiverse-Core, Multiverse-Inventories, MyCommand, NametagEdit*, OldCombatMechanics*, OpenInv*, Ping*, PlaceholderAPI, PlayerReport*, PlugMan, PremiumVanish, ProtocolLib*, RankGrantPlus, Residence, ShowInventory*, SignEdit*, SkinsRestorer, SlotMachine, TitleManager*, Towny*, TrollCommandsPlusPlus, Vault*, WirelessRedstone, WorldEdit, WorldGuard

**How to replicate**:
1. Go to a normal world
2. Find a place with trees
3. Execute //replacenear [whatever radius] [type]_leaves air
4. Result expected: 0 blocks affected

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure the bug/error is not caused by any other plugin
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug is only present in FAWE, not regular WorldEdit (Extra check)

**Comment by Tsoccerguy3** [comment]
Not sure , but this might be related to , /forestgen anything , then do a //undo , there will be leaves , vines etc left behind . that need to be remove with other commands
