### ISSUE TITLE
Worldguard builds #1849 and newer , no longer load with FAWE breaking builds

### ISSUE THREAD

**Issue by Tsoccerguy3** [IntellectualSites/FastAsyncWorldEdit-1.13#142]
Worldguard builds #1849 and newer , no longer load with FAWE "breaking" builds

Worldguard build #1847 Works with breaking builds

issue does not exist with builds of Worldedit #4253 and below

Tested FastAsyncWorldEdit-bukkit-1.13.108 and some commits for this week , have the same results . most likely the issue goes back to the days around the Worldguard #1849 build date

found this when updating worldguard today 

Server Paper624

Error
4:46:27 PM [javastacktrace] 	at com.sk89q.worldguard.WorldGuard.<init>(WorldGuard.java:70) ~[?:?]
4:46:27 PM [javastacktrace] 	at com.sk89q.worldguard.WorldGuard.<clinit>(WorldGuard.java:62) ~[?:?]
4:46:27 PM [javastacktrace] 	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:134) ~[?:?]
4:46:27 PM [javastacktrace] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
4:46:27 PM [javastacktrace] Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.internal.command.exception.ExceptionConverterHelper
4:46:27 PM [javastacktrace] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
4:46:27 PM [javastacktrace] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-624]
4:46:27 PM [javastacktrace] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
4:46:27 PM [javastacktrace] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
4:46:27 PM [javastacktrace] java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.WorldGuard
4:46:27 PM [javastacktrace] 	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onDisable(WorldGuardPlugin.java:213) ~[?:?]

**Comment by yannicklamprecht** [comment]
That's normal. WorldGuard depends on the latest version of Worledit with all the classes present there. FAWE didn't get the upstream of Worldedit for a "long" time. So the new classes aren't available there.

**Comment by AeSix** [comment]
FAWE is, as far as I know is still, being developed against WorldEdit 7 beta 5 and WoldGuard 7 beta 3, and thus has not compatibility guarantee with any snapshot newer (or older) than these betas. 

When WE/WG release new betas, the devs will work toward them. 

Please close this ticket, at least until such time as the next beta (or stable) WG is released.

**Comment by Tsoccerguy3** [comment]
closed

**Comment by Tsoccerguy3** [comment]
Reopened , Worldguard 7 final released Worldedit 7 final released

**Comment by Tsoccerguy3** [comment]
The Worldguard and worldedit API's , should really be updated to the latest stable . using beta 3 may satisfy FAWEs conditions but it breaks newer plugins as they are released .
