### ISSUE TITLE
1.14(.1) version

### ISSUE THREAD

**Issue by lukaskabc** [IntellectualSites/FastAsyncWorldEdit-1.13#145]
Hi,
what about FAWE and update for version 1.14....1.14.1 ?

Thanks for answer.

**Comment by Tsoccerguy3** [comment]
Initial commit compiles , dont expect it to be server friendly
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/tree/breaking-114

**Comment by MattBDev** [comment]
Stop asking
