### ISSUE TITLE
Setting a tile entity where a hopper exists can cause a crash

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/FastAsyncWorldEdit-1.13#148]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

```
[03:58:17 INFO]: [FAWE] FastAsyncWorldEdit-1.13-110 by Empire92
[03:58:17 INFO]: ------------------------------------
[03:58:17 INFO]:  - DATE: May 12, 2019 12:00:00 AM
[03:58:17 INFO]:  - COMMIT: e72a5cf
[03:58:17 INFO]:  - BUILD: 110
[03:58:17 INFO]:  - PLATFORM: bukkit
[03:58:17 INFO]: ------------------------------------
[03:58:17 INFO]: Platforms:
[03:58:17 INFO]:  - Bukkit
[03:58:17 INFO]: Capabilities:
[03:58:17 INFO]:  - GAME_HOOKS: Bukkit
[03:58:17 INFO]:  - CONFIGURATION: Bukkit
[03:58:17 INFO]:  - USER_COMMANDS: Bukkit
[03:58:17 INFO]:  - PERMISSIONS: Bukkit
[03:58:17 INFO]:  - WORLDEDIT_CUI: Bukkit
[03:58:17 INFO]:  - WORLD_EDITING: Bukkit
[03:58:17 INFO]: ------------------------------------
```

**[REQUIRED] Spigot/Paper Version Number:** 

`CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

**Links to config.yml and config-legacy.yml file:** 

config.yml: https://hastebin.com/omelusogen.yml
config-legacy.yml: https://hastebin.com/ewenosuciv.yml

**[REQUIRED] Description of the problem:**

Relevant log: https://hastebin.com/ciqosoboku.md

**Plugins being used on the server:**

CleanroomGenerator, CoreProtect, WorldEdit, FastAsyncWorldEdit, FastAsyncVoxelSniper, PermissionsEx, PlotSquared, BanManager, WorldGuard, ProtocolLib, Multiverse-Core, VanishNoPacket, SynergyCore, SynergyLobby, Multiverse-Inventories, ArmorStandTools, SynergySurvival, Multiverse-NetherPortals, BuycraftX, SynergyCreative

**How to replicate**:

Place a hopper, select it, then do `//set comparator` and the server should crash

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by zombachu** [comment]
Update: Seems to be any tile entity replacing a hopper can cause a crash
Tested with a dropper, furnace, chest, beacon, banner, and daylight sensor for now

**Comment by N0tMyFaultOG** [comment]
I was able to reproduce it, however I cannot seem to crash a server with it, the only thing that appears is this short message: 
`Block at -66,69,308 is Block{minecraft:comparator} but has net.minecraft.server.v1_13_R2.TileEntityFurnace@1bf1a8a8. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`
while having items in the dropper, furnace and so on.

**Comment by zombachu** [comment]
@N0tMyFaultOG It's the comparator that can be any tile entity to cause a crash, the original block being replaced needs to be a hopper

**Comment by zombachu** [comment]
Seems like this and #149 may have to do with tileEntityListTick in net.minecraft.server.World being out of sync with the actual world but I don't know enough about the inner workings of FAWE or Minecraft to look towards fixing this myself
