### ISSUE TITLE
Problem with fawe region restriction

### ISSUE THREAD

**Issue by monkey8113** [IntellectualSites/FastAsyncWorldEdit-1.13#153]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
[02:30:47] (FAWE) FastAsyncWorldEdit 1.13-19.5.6-55b02e1-108 by Empire92

[02:30:47] ------------------------------------

[02:30:47] - DATE: May 6, 2019 12:00:00 AM

[02:30:47] - COMMIT: 55b02e1

[02:30:47] - BUILD: 108

[02:30:47] - PLATFORM: bukkit

[02:30:47] ------------------------------------

[02:30:47] Platforms:

[02:30:47] - Bukkit (1.13.108)

[02:30:47] Capabilities:

[02:30:47] - GAME_HOOKS: Bukkit

[02:30:47] - CONFIGURATION: Bukkit

[02:30:47] - USER_COMMANDS: Bukkit

[02:30:47] - PERMISSIONS: Bukkit

[02:30:47] - WORLDEDIT_CUI: Bukkit

[02:30:47] - WORLD_EDITING: Bukkit

[02:30:47] ------------------------------------

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-625 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Links to config.yml and config-legacy.yml file:** 
config.yml
https://pastebin.com/ySbkPax0

config-legacy.yml
https://pastebin.com/z8YRQz8s

**[REQUIRED] Description of the problem:**
Console show
com.sk89q.worldedit.regions.CuboidRegion$2$1: End of iterator

Error shows in server is different for each command.
basically what happen is when someone stack a build, the fawe only work in the chunk the person is standing in, error like these would show.
This outside allowed region bypass with /wea or disable region-restriction in config yml

Im aware i need to give region permission, ive given all fawe permission related to worldguard and towny

**Plugins being used on the server:**
couple of plugins but ill list some that might relate
-luckperms
-fawe
-coreprotect
-blockshub
-essentials
-worldguard 
-towny

**How to replicate**:
just try to stack builds or copy something bigger than one chunk, the builds would only be pasted in the chunk you are standing in.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
@monkey8113 Can you test it with the last version?

I can't replicate this issue.

`tested with FastAsyncWorldEdit (1.13.146) and PlotSquared (4.297) in PaperSpigot 1.13.2 (632)`

**Comment by RedstoneFuture** [comment]
Right.
`tested with FastAsyncWorldEdit (1.13.146) and PlotSquared (4.297) in PaperSpigot 1.13.2 (632)`

**Comment by ipozow** [comment]
Same issue here. I have also made a video: https://youtu.be/phDoTdt1zBc
My config is different anyways, town_block_size: is set to '32'

**Comment by ipozow** [comment]
Is not fixed, I am using FastAsyncWorldEdit-bukkit-1.13.204

**Comment by N0tMyFaultOG** [comment]
The issue is fixed in commanding, means for 1.14 builds. That is the priority right now.
