### ISSUE TITLE
1.13 //hollow erases selection

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/FastAsyncWorldEdit-1.13#160]
Debugpaste: https://athion.net/ISPaster/paste/view/c83e406989474acd8aea659bd553e4ee

How to Replicate:

Make a solid object (in this example I just made a cube)
https://brdv.coffee/storage/uploads/4/AtXswpGlUSYA.png

Type //hollow
The object disappears 
https://brdv.coffee/storage/uploads/4/nqn3CjmUTBxb.png

**Comment by PixelNotFound** [comment]
If you want a gif for more details: https://github.com/boy0001/FastAsyncWorldedit/issues/1299

**Comment by PixelNotFound** [comment]
I hope it gets patched soon

**Comment by MattBDev** [comment]
I'm working on fixing this soon.

**Comment by PixelNotFound** [comment]
Great!

**Comment by IronApollo** [comment]
Fixed in e2c2205dac455ee14a3e58acc91b01737060bae6
