### ISSUE TITLE
"//copy" - java.lang.IllegalStateException: key must be lowercase

### ISSUE THREAD

**Issue by BlackBeltPanda** [IntellectualSites/FastAsyncWorldEdit-1.13#161]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
(FAWE) FastAsyncWorldEdit-1.13-115 by Empire92
------------------------------------
- DATE: May 30, 2019 12:00:00 AM
- COMMIT: aea5b68
- BUILD: 115
- PLATFORM: bukkit
------------------------------------
Platforms:
- Bukkit
Capabilities:
- GAME_HOOKS: Bukkit
- CONFIGURATION: Bukkit
- USER_COMMANDS: Bukkit
- PERMISSIONS: Bukkit
- WORLDEDIT_CUI: Bukkit
- WORLD_EDITING: Bukkit

**[REQUIRED] Spigot/Paper Version Number:** 
Paper version git-Paper-626 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Links to config.yml and config-legacy.yml file:** 
config.yml: https://pastebin.com/raw/pYeuJxdB
config-legacy.yml: https://pastebin.com/raw/pfnsNT4t

**[REQUIRED] Description of the problem:**
When running the command, "//copy", the following error occurs: https://pastebin.com/raw/C3WEzEuk

**Checklist**:
- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Tsoccerguy3** [comment]
This commit aea5b68ced63511b0e0c13b3a94c5582b9d013e9 also breaks 
//copy then //flip then //paste ,  will paste nothing . when  you //flip the clipboard , the array is empty and paste nothing

**Comment by BlackBeltPanda** [comment]
I found that running "//copy -e" instead of just "//copy" works and doesn't throw any errors.

**Comment by MattBDev** [comment]
Fixed in the next commit.
