### ISSUE TITLE
//smooth 50 -s produces out of bounds error

### ISSUE THREAD

**Issue by Tobberz** [IntellectualSites/FastAsyncWorldEdit-1.13#166]
# Bug report for FastAsyncWorldEdit 1.13.2

**FastAsyncWorldEdit Version Number:** FastAsyncWorldEdit-1.13-120

**Spigot/Paper Version Number:** git-Paper-629 (MC: 1.13.2)

**Links to config.yml and config-legacy.yml file:** 
Config: https://pastebin.com/mGgTYHRr
Legacy Config: https://pastebin.com/tswG5Egj

**Description of the problem:**
>Very similar error reported on 1.12: [[Link]](https://github.com/boy0001/FastAsyncWorldedit/issues/1276)
>Error created when using //smooth 50 -s
>Error paste: https://pastebin.com/VcWu219U

**How to replicate**:
>Any player in (seemingly) any region uses said command.

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by PixelNotFound** [comment]
Havind same issue.

**Comment by StealWonders** [comment]
Can replicate.
