### ISSUE TITLE
Replace-tool doesn't work with NBT-Data

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit-1.13#169]
The replace tool (/repl <blockid>) does not work correctly with blocks containing NBT data. If you select a part of a bed, a labeled sign or a head with left click, the selected block is invisible after replacing with right click. 
If you use the normal selection with //copy and //paste for this operation, the blocks will be set correctly without problems.  

FAWE 1.13.128
Paper 1.13.2 - 628

**Comment by RedstoneFuture** [comment]
@TheoRetisch1 Do you have example commands? / A exactly situation?

If I select the head part of this bed the replace works.

![2019-06-26_23 14 38](https://user-images.githubusercontent.com/4140635/60215661-63ce5c80-9868-11e9-8f67-eefc3965ff34.png)
