### ISSUE TITLE
//center doesnt work perfectly

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#17]
expectation:

type //center <material> after selecting a region with an even number of blocks wide / long
It should replace the central 4 blocks with X material

What occurs: The red / blue wool are my pos1 and pos2
and when i type //center white_wool it doesnt center perfectly.

the black wool should be white too. 
![2019-01-16_10 33 22](https://user-images.githubusercontent.com/22693741/51263821-a49d7d80-197a-11e9-8d27-16bc4a579194.png)

Using vector update IronApollo sent me and
CraftBukkit version git-Spigot-f56e2e7-0c715b3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT

**Comment by RealmportalMC** [comment]
@IronApollo

**Comment by AeSix** [comment]
This is confirmed to still be an issue with FAWE-NVS 165
https://puu.sh/D30Ds/f4ae6a79d2.png

**Comment by Sauilitired** [comment]
Fixed in NVS =)
