### ISSUE TITLE
Crash on Java 12

### ISSUE THREAD

**Issue by EsGibtKeineMitte** [IntellectualSites/FastAsyncWorldEdit-1.13#174]
Well while using Java 12 the FAWE injection does not work.

I've commented out the bukkit.getServer().shutdown() to get the full stacktrace:

https://pastebin.com/A98jjEyZ

MfG
Leonhard|EsGibtKeineMitte

**Comment by MattBDev** [comment]
Don't use Java 12. It breaks a lot. Use Java 9 or Java 8

**Comment by Raster556** [comment]
Java is updating fast and I would think it is best to resolve depreciated java functions so users can use your plugin with newer versions of java if for some reason they need it.

**Comment by MattBDev** [comment]
@Raster556 Minecraft is still using Java 8 and has no reason to update to a newer version of java yet. There are many other bigger issues with the plugin to worry about.
