### ISSUE TITLE
FAWE Crash (Failed to create shape)

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit-1.13#176]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.144

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/s51kTVcn
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
Someone was able to crash my server, I'm assuming it's because they used `//g -c -h Coal_block (200-sqrt(x^2+z^2))^2+y^2<30^2` the bottom of the log mentions something about failing to create a shape.

Log: https://pastebin.com/5ZTkeFpQ

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
`/plugins/FastAsnycWorldEdit/config-legacy.yml` -> calculation.timeout
Which value did you put in there?

**Comment by SecretlyJealous** [comment]
> `/plugins/FastAsnycWorldEdit/config-legacy.yml` -> calculation.timeout
> Which value did you put in there?

100

**Comment by N0tMyFaultOG** [comment]
Hm, maybe try a smaller region? I couldn't reproduce it using `#163`

**Comment by SecretlyJealous** [comment]
This happened on my live server so when I tried doing it on a test server it didn't cause any issues, I'm going to try doing this again when there are a lot of players online on the live server
