### ISSUE TITLE
Could not pass event BlockPhysicsEvent to WorldEdit v1.13.17

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit-1.13#180]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.144

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/s51kTVcn
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
Got this error in my log, not too sure what causes it
Log: https://pastebin.com/3zC7HJ6d

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Brushes can't be bound to your hand anymore. Aside that, `v1.13.17` is very outdated.

**Comment by Tsoccerguy3** [comment]
> 
> 
> Brushes can't be bound to your hand anymore. Aside that, `v1.13.17` is very outdated.
NotMyFault , could you not just close these issues when they are a dupp of a previous know issue ? I know there are many ways to say the same thing , but this is the API issue is it not ?

Secret , 
Fawe 1.13.144 is still using the outdated worldguard and worldedit API's ie ... Worldedit beta 5 and worldguard beta 3 . unless updated to current stable Fawe will break  some compatibility of the newer plugins . You can't have the newer plugins and Fawe together , something is going to break . Newer Worldguard will not load , etc ... These issues are already known . NotMyFault and MattDev and Boy001 are in process of updating .
