### ISSUE TITLE
What gradle version should i use?

### ISSUE THREAD

**Issue by crazybytes** [IntellectualSites/FastAsyncWorldEdit-1.13#184]
What gradle version should i use?
Thanks in advance.

Things like this and so on...

> Task :worldedit-core:compileJava
/root/FastAsyncWorldEdit-1.13/worldedit-core/src/main/java/com/boydti/fawe/installer/BrowseButton.java:7: error: package javafx.application does not exist
import javafx.application.Platform;

I tried several gradle versions, ubuntu, windows.....

**Comment by Draycia** [comment]
JavaFX is not bundled with openjdk. You must install it separately.

**Comment by MattBDev** [comment]
openjfx
