### ISSUE TITLE
> repository not found: /root/.gradle/daemon/4.10.2/.git

### ISSUE THREAD

**Issue by crazybytes** [IntellectualSites/FastAsyncWorldEdit-1.13#185]
Thanks for the previous quick response....

Having other problem...
 ./gradlew build
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip
...............................................................................................................
blah blah
...
FAILURE: Build failed with an exception. (RED color, red.)

* Where:
Build file '/root/f/build.gradle' line: 44

* What went wrong:
A problem occurred evaluating root project 'FastAsyncWorldEdit'.
> repository not found: /root/.gradle/daemon/4.10.2/.git

**Comment by MattBDev** [comment]
This is actually an issue with gradle and not FAWE. I'm not sure how to fix it though.

**Comment by crazybytes** [comment]
Ok. Thanks.

Op di 9 jul. 2019 om 21:45 schreef Matt <notifications@github.com>:
