### ISSUE TITLE
he Task.leftShift(Closure) method has been deprecated.

### ISSUE THREAD

**Issue by crazybytes** [IntellectualSites/FastAsyncWorldEdit-1.13#186]
> Configure project :worldedit-bukkit
The Task.leftShift(Closure) method has been deprecated. This is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_3dpz3ec9ir2a0ssqfdvsb1uro.run(C:\work\f\worldedit-bukkit\build.gradle:48)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

**Comment by crazybytes** [comment]
Ok. I did a lot. But now i use the -master edition. It seems larger... 
Its a mixed up world....

**Comment by crazybytes** [comment]
Maybe a list included with:

JAVA
JAVA SDK
GRADLE
etc.
How to download them.
What to include.
Where to find it.
How to install it.
Etc.
A complete recipe.
(Just suggesting.)
(now i need java 12....)

**Comment by MattBDev** [comment]
The issue doesn't occur on the breaking branch so I am closing. Please consider discussing these things on discord instead of opening issues.

**Comment by crazybytes** [comment]
Yes.
What is discord? ...

Op di 9 jul. 2019 om 22:30 schreef Matt <notifications@github.com>:
