### ISSUE TITLE
Organize translations into a dedicated folder

### ISSUE THREAD

**Issue by Leonardo-DGS** [IntellectualSites/FastAsyncWorldEdit-1.13#189]
FAWE translations should be in a dedicated folder considering that putting them into the main folder makes a mess.

**Comment by N0tMyFaultOG** [comment]
Translations should be moved to a translations folder like PlotSquared does.

**Comment by MattBDev** [comment]
Translations will be addressed once this PR in WorldEdit is merged EngineHub/WorldEdit#478
