### ISSUE TITLE
Huge edits (like 200^3) causes TPS loss

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#19]
i selected a large area about 200 x 200 x 200 and did //set stone

The server dropped to about 15 to 16 TPS. This didnt happen even with a 2 billion block edit back on 1.12.2

Using IronAPollos vector Update

**Comment by RealmportalMC** [comment]
@IronApollo

**Comment by RealmportalMC** [comment]
/br height
seems to also cause massive TPS loss

**Comment by AeSix** [comment]
I selected 200^3 area with FAWE-NVS 165
I then //set stone

The operation took about 7-10 seconds.
The TPS dropped down to 19.95 from 19.99

There was no noticeable latency in the game.  In earlier builds, the server would had crashed for such an operation.
