### ISSUE TITLE
NullPointerException with //replace

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit-1.13#191]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.170

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/s51kTVcn
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
Got a NullPointerException when someone tried using `//replace 0 109`
Log: https://pastebin.com/8DEYb5j2

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
With the change from 186 to version 187 the "//replace" command have a problem.


`[00:22:02] [Server thread/INFO]: RedstoneFuture issued server command: //replace 1 2
[00:22:02] [Craft Scheduler Thread - 7/INFO]: Using adapter: com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2@dc1e45
[00:22:02] [Craft Scheduler Thread - 7/INFO]: =========================================
[00:22:02] [Craft Scheduler Thread - 7/ERROR]: An unexpected error occurred while handling a FAWE command
com.sk89q.worldedit.regions.CuboidRegion$2$1: End of iterator
[00:22:02] [Server thread/INFO]: (FAWE) Having `parallel-threads` > 1 interferes with the timings.`

testet with paper 624
