### ISSUE TITLE
Missing ExceptionConverterHelper.java is causing the WorldGuard incompatibility

### ISSUE THREAD

**Issue by acrylic-style** [IntellectualSites/FastAsyncWorldEdit-1.13#193]
# Bug report for FastAsyncWorldEdit __1.14.3__ (breaking-114)

**[REQUIRED] FastAsyncWorldEdit Version Number:**

```
FastAsyncWorldEdit-1.14-7 by Empire92
----------- Platforms -----------
 - DATE: 2019/07/11 0:00:00
 - COMMIT: f0cabb7
 - BUILD: 7
 - PLATFORM: bukkit
------------------------------------
----------- Platforms -----------
* Bukkit
----------- Capabilities -----------
 - GAME_HOOKS: Bukkit
 - CONFIGURATION: Bukkit
 - USER_COMMANDS: Bukkit
 - PERMISSIONS: Bukkit
 - WORLDEDIT_CUI: Bukkit
 - WORLD_EDITING: Bukkit
----------------------------------------
```

**[REQUIRED] Spigot/Paper Version Number:** 

```
This server is running Paper version git-Paper-127 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)
```

**Links to config.yml and config-legacy.yml file:** 

[debugpaste here](https://athion.net/ISPaster/paste/view/a23eb7bb24c643478cda761a10060f7f)

**[REQUIRED] Description of the problem:**

Missing [ExceptionConverterHelper.java](https://github.com/EngineHub/WorldEdit/blob/master/worldedit-core/src/main/java/com/sk89q/worldedit/internal/command/exception/ExceptionConverterHelper.java) (This file was created about 2 months ago) is causing the WorldGuard(`7.0.1-beta-01;14e7525` and/or `v7.0.0;02b731f`) incompatiblity

**Plugins being used on the server:**

```
 - FastAsyncWorldEdit: 1.13-breaking
 - WorldEdit: 1.14.7
 - WorldGuard: 7.0.1-beta-01;14e7525
```

**How to replicate**:

Install WorldGuard from [here](https://dev.bukkit.org/projects/worldguard/files/2723618/download)
then install FAWE from [here](https://ci.athion.net/view/Everything/job/FastAsyncWorldEdit-1.14/7/artifact/target/FastAsyncWorldEdit-bukkit-1.14.7.jar) and start the server

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
I used the last successful build of [FastAsyncWorldEdit for 1.14.3](https://ci.athion.net/view/Everything/job/FastAsyncWorldEdit-1.14/7/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Tsoccerguy3** [comment]
This is a Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/142

**Comment by acrylic-style** [comment]
I saw that issue but I didn't see the stacktrace :(
It was same stacktrace, i'll close this issue.

**Comment by yannicklamprecht** [comment]
This constellation works without problems:
- Spigot-1.14.3
- FastAsyncWorldedit Latest build for 1.14.3
- WorldGuard 7.0.0 beta 3

**Comment by acrylic-style** [comment]
Oh, WorldGuard 7.0.0 beta 3 worked for me too. but any newer versions are incompatible.
