### ISSUE TITLE
Basic feature problems | //flip //rotate //paste -o [In plugin -> makeWalls()]

### ISSUE THREAD

**Issue by SkykillerTV** [IntellectualSites/FastAsyncWorldEdit-1.13#195]
Hello :)

I'm a Plugin-Developer and I test some basic features and these are my results.
`https://paste.myplayplanet.net/urexubeyah.sql`

I write an own Method for my Plugin and for that I use editSession.makeWalls().
But also editSession.replace throws an StackOverflowException.
Same Exception like makeWalls(); -> `http://prntscr.com/og9txl`

To create an EditSession I use this:
`EditSession editSession = new EditSessionBuilder(new BukkitWorld(p.getWorld())).fastmode(false).build();`

**Comment by SkykillerTV** [comment]
Okey I and a friend test paste and set 0 and if you copy a hopper and try to paste it then the console throw this error:
http://prntscr.com/ogc2si

Reproduce:
Place HOPPER -> //copy and then //set or //paste -o -> throws error

**Comment by Tsoccerguy3** [comment]
Your testing FAWE breaking_114 , nothing works yet , maybe a few things , but not enough to use it . It is also using old 1.3 beta API's and being compiled with java 8 .  Using FAWE at this time on your server will probably break compatibility with plugins that are compatible with 1.14.x API's and Java 12

**Comment by N0tMyFaultOG** [comment]
If you have questions about the api, head over to our discord -> #programming :)
