### ISSUE TITLE
Null Pointer on /fawe in console

### ISSUE THREAD

**Issue by urtext** [IntellectualSites/FastAsyncWorldEdit-1.13#196]
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
Due to the nature of this report, i am unable to directly copy this;

Date: 16-jul-2019 00:00:00
Commit: 4835627
Build: 173
platform: bukkit

Plateforms: Bukkit

Capabilities:
 - GAME_HOOKS: Bukkit
 - CONFIGURATION: Bukkit
 - USER_COMMANDS: Bukkit
 - PERMISSIONS: Bukkit
 - WORLDEDIT_CUI: Bukkit
 - WORLD_EDITING: Bukkit

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.

**Links to config.yml and config-legacy.yml file:** 
Config: https://pastebin.com/1y22DBEM
Config-legacy: https://pastebin.com/w9QBYV7S

Also, the stack itself: https://pastebin.com/NTwNDDCc

**[REQUIRED] Description of the problem:**
I was trying to get the version through console for another issue report, however received this error whenever using /fawe, im unsure if this is related to the original issue, however commands such as //wand, etc work fine. 

**Plugins being used on the server:**
EssentialsX, EssentialsXChat, Fawe, GroupManager, WorldGuard(Legacy 8.0 beta 09 build) & UseMore(Custom plugin that uses fawe)

**How to replicate**:
Simply executing the command "/awe" in console seems to through the error. However, the command works perfectly fine ingame(Hence how i was about to still get it), I have tried a server restart with the same result.

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
With the removal of FakePlayer, fawe cannot be used from console right now.
