### ISSUE TITLE
disallowed-blocks is bypassable

### ISSUE THREAD

**Issue by ChimpGamer** [IntellectualSites/FastAsyncWorldEdit-1.13#199]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.13-170 by Empire92
----------- Platforms -----------
 - DATE: Jul 10, 2019 12:00:00 AM
 - COMMIT: 2c76c23
 - BUILD: 170
 - PLATFORM: bukkit
------------------------------------
----------- Platforms -----------
* Bukkit
----------- Capabilities -----------
 - GAME_HOOKS: Bukkit
 - CONFIGURATION: Bukkit
 - USER_COMMANDS: Bukkit
 - PERMISSIONS: Bukkit
 - WORLDEDIT_CUI: Bukkit
 - WORLD_EDITING: Bukkit
------------------------------------
Wiki: https://github.com/boy0001/FastAsyncWorldedit/wiki

**[REQUIRED] Spigot/Paper Version Number:** 
PaperSpigot v1.13.2 b639

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/cdE2aJLF
https://pastebin.com/xAVdgLd9

**[REQUIRED] Description of the problem:**
Players can bypass the disallowed-blocks list by using lowercase material names or block id's

**Plugins being used on the server:**

**How to replicate**:
Obvious

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Follow the template and complete the checklist before raising an issue.

**Comment by ChimpGamer** [comment]
I don't get what I missed?

**Comment by N0tMyFaultOG** [comment]
![](https://i.imgur.com/HnrCCZU.png)
Simply where you did not set an `x`. Your version is outdated, which indicates you didn't even went thru it.

**Comment by ChimpGamer** [comment]
The changes that were made in the last five builds are not relevant to this problem, so that won't change a thing. I see I forgot to check the last one.
