### ISSUE TITLE
Sand falls and cant be undone

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#20]
Sand follows Normal physics behavior and falls

//undo doesnt fix it3.

IronApollos Vector Update version

**Comment by RealmportalMC** [comment]
@IronApollo

**Comment by RealmportalMC** [comment]
Edit: it falls if more than 1 block of sand is changed adjacent to each other.
If i //set 1 block of sand it floats

**Comment by RealmportalMC** [comment]
Appears to affect all blocks that fall including anvils

**Comment by AeSix** [comment]
I can confirm this is still an issue with FAWE-NVS 165

This is probably going to be a symptom of the same cause as https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/66 and https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/67

**Comment by N0tMyFaultOG** [comment]
Fixed in latest fawe-breaking
