### ISSUE TITLE
disallowed-blocks does not work

### ISSUE THREAD

**Issue by ChimpGamer** [IntellectualSites/FastAsyncWorldEdit-1.13#200]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.13-176 by Empire92
----------- Platforms -----------
 - DATE: Jul 23, 2019 12:00:00 AM
 - COMMIT: 56ddc40
 - BUILD: 176
 - PLATFORM: bukkit
------------------------------------
----------- Platforms -----------
* Bukkit
----------- Capabilities -----------
 - GAME_HOOKS: Bukkit
 - CONFIGURATION: Bukkit
 - USER_COMMANDS: Bukkit
 - PERMISSIONS: Bukkit
 - WORLDEDIT_CUI: Bukkit
 - WORLD_EDITING: Bukkit
------------------------------------
Wiki: https://github.com/boy0001/FastAsyncWorldedit/wiki

**[REQUIRED] Spigot/Paper Version Number:** 
PaperSpigot v1.13.2 b641

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/cdE2aJLF
https://pastebin.com/xAVdgLd9

**[REQUIRED] Description of the problem:**
Players can still set any type of "block" that is on the blacklist and they have no bypass permission. This is very frustrating because they keep crashing the server with some type of blocks.

**Plugins being used on the server:**

**How to replicate**:
Obvious

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dextonanderson** [comment]
Try formatting it like this:
`disallowed-blocks: [minecraft:cobblestone,minecraft:dirt,etc]`
