### ISSUE TITLE
Empty command blocks after flip/rotate

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit-1.13#202]
The contents of command blocks are not copied when rotated or flipped. Flipped or rotated command blocks are simply blank after being pasteted.

The test was done using a newly generated config and a newly generated DUMMY file.
FAWE 1.13.176
Paper 1.13.2 - 641

**Comment by Tsoccerguy3** [comment]
//flip , //rotate and the paste are broken for everything not just command blocks

**Comment by SirYwell** [comment]
Most likely the same Problem as #71. I'll close this one therefore.
