### ISSUE TITLE
Tab complete listing usernames

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit-1.13#209]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.178

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/s51kTVcn
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
After the required arguments for a worldedit command have been typed usernames will be listed in tab complete. In this example I'm using //set which only requires one argument and after I have specified an argument pressing space will keep listing usernames.
![Tab1](https://user-images.githubusercontent.com/10485646/63025976-3d10c780-bea2-11e9-9635-4e79056351ab.png)

It acts very strange with arguments that require multiple arguments such as //replace for example which requires two arguments. In this example I'm using //replace and the second argument will list usernames:
![Tab2](https://user-images.githubusercontent.com/10485646/63026189-9f69c800-bea2-11e9-9b34-e5aba1363ad3.png)

As soon as I start typing a letter for the second argument the tab complete removes the usernames and shows the block names:
![Tab3](https://user-images.githubusercontent.com/10485646/63026304-dc35bf00-bea2-11e9-9f6f-2a601928c74a.png)
Doing another space after that will just keep listing usernames.

This behaviour in general is strange because I assumed that the listing username stuff would dissapear by disabling this config option in paper: 
`suggest-player-names-when-null-tab-completions: false`
Having this option set to false removes usernames from being listed when using other commands however FAWE still lists usernames once the arguments have been typed in. My own commands don't have this behaviour:
![msg prompt](https://user-images.githubusercontent.com/10485646/63026640-75fd6c00-bea3-11e9-8193-3cf8da1c5e60.png)
![Untitled](https://user-images.githubusercontent.com/10485646/63027094-397e4000-bea4-11e9-95bb-8d4e27ba9919.png)

![msg second prompt](https://user-images.githubusercontent.com/10485646/63026880-d7bdd600-bea3-11e9-9f8e-7da22dcebaed.png)
![Untitled](https://user-images.githubusercontent.com/10485646/63026889-dab8c680-bea3-11e9-9802-d0e36909b749.png)

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Merge does currently not support tab complete items. Yet if https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/256 gets fixed, this one should be resolved as well.

**Comment by lwd-adam** [comment]
This is a setting in paper.yml.

**Comment by SecretlyJealous** [comment]
> This is a setting in paper.yml.

The setting in paper.yml doesn't change the behavior of this at all. "suggest-player-names-when-null-tab-completions: false" still suggests player names on fawe commands.
