### ISSUE TITLE
WorldEdit server crash

### ISSUE THREAD

**Issue by BenDoesArt** [IntellectualSites/FastAsyncWorldEdit-1.13#218]
My entire server crashes when I use worldedit for a medium or large selection.
# It is meant to provide us at IntellectualSites with better information about your problem

# Server Information
Server Platform: bukkit
Server Version: git-Spigot-1a3504a-dfa7583 (MC: 1.13.2)
Plugins: 
 - dynmap: 3.0-beta-5-218
 - WorldEdit: 1.13.180
 - PlaceholderAPI: 2.10.3
 - ClearLag: 3.0.6
 - DisableJoinMessage: 1.0
 - PlugMan: 2.1.6
 - Animatronics: 2.2.4.1
 - WorldGuard: 7.0.0-beta-03;e51a220
 - FastAsyncWorldEdit: 1.13-breaking
 - goPaint: 2.2.0
 - ViaVersion: 2.1.3
 - UltraPermissions: 4.2.9
 - ArmorStandTools: 3.4.0
 - MCJukebox: 2.6.5
 - ProtocolLib: 4.4.0
 - HideAndCustomPlugins: 1.8.1
 - iDisguise: 5.8.2
 - Vault: 1.7.2-b107
 - GUIPlus: 1.25
 - Essentials: 2.17.1.15
 - BKCommonLib: 1.13.2-v3
 - NamelessMC: beta-29
 - BuycraftX: 12.0.2
 - LiteBans: 2.3.18
 - DecoHeads: 1.5.0
 - DeluxeChat: 1.13.2
 - EssentialsProtect: 2.17.1.15
 - Train_Carts: 1.13.2-v1
 - EssentialsChat: 2.17.1.15
 - TimeIsMoney: 1.9.6.8
 - ItemJoin: 5.0.3
 - EssentialsSpawn: 2.17.1.15
 - TitleManager: 2.1.5
 - TCCoasters: 1.13.2-v1

**Comment by SirYwell** [comment]
Please follow the given issue template. We can't help you otherwise.
