### ISSUE TITLE
ConcurrentModificationException with //gmask

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit-1.13#235]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:**
FastAsyncWorldEdit-bukkit-1.13.179

**[REQUIRED] Spigot/Paper Version Number:**
paper build 637

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/XuhJEDjM
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
Given a ConcurrentModificationException: null error in console, probably from //gmask grass podzol,dirt,coarse_dirt,grass,green_wool,green_terracotta
Error: https://pastebin.com/mKhbAB7r

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**How to replicate**:
//gmask grass podzol,dirt,coarse_dirt,grass,green_wool,green_terracotta

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Not fixed in commanding yet, seems to be hard-limited now?
![](https://i.imgur.com/UG9GE6Q.png)

**Comment by boy0001** [comment]
You get too many arguments, because the command is `//gmask <mask>` not `//gmask <mask> <mask>`. I dont get the error in latest build.
