### ISSUE TITLE
Entity copy and pasting doesnt work

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#24]
copy to clipboard (with entities)

//paste
entites dont copy.

Using @IronApollo s vector update

**Comment by AeSix** [comment]
I can confirm this is still an issue with FAWE-NVS 165
Tested with parrots and minecarts.
Both copy/paste and //stack fail to duplicate the entities.

**Comment by Tsoccerguy3** [comment]
confirmed , still issue with FAWE breaking build 144

**Comment by N0tMyFaultOG** [comment]
Duplicate of https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/71
