### ISSUE TITLE
PlotSquared claim or autoclaim doesn't work with FAWE lastest version.

### ISSUE THREAD

**Issue by fhebuterne** [IntellectualSites/FastAsyncWorldEdit-1.13#240]
# Bug report for FastAsyncWorldEdit 1.13.2

**[REQUIRED] FastAsyncWorldEdit Version Number:** FastAsyncWorldEdit-1.13-186 by Empire92

**[REQUIRED] Spigot/Paper Version Number:** Paper version git-Paper-651 (MC: 1.13.2)

**Links to config.yml and config-legacy.yml file:** Default Configs

**[REQUIRED] Description of the problem:**

When i want to claim or autoclaim with plotsquared, i have this error :
https://pastebin.com/nFNnYX9X

**How to replicate**:
- Install last plotsquared and fawe version and try to plot claim or autoclaim.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Don't report this here.

**Comment by MattBDev** [comment]
What I meant to say was, it is a known issue and we have been trying to fix it for weeks. It's an issue with our CI. If you need a fix you need to compile the plugin on your own.

**Comment by fhebuterne** [comment]
> What I meant to say was, it is a known issue and we have been trying to fix it for weeks. It's an issue with our CI. If you need a fix you need to compile the plugin on your own.

Thanks for fast anwser but i have tried to compile and install myself, i have same issue : https://pastebin.com/YxFgKTZU

**Comment by MattBDev** [comment]
I need to know the specific version number of PlotSquared you have installed.

**Comment by fhebuterne** [comment]
PlotSquared version 4.353 (latest version available on spigot)

**Comment by MattBDev** [comment]
Update to the latest plotsquared breaking build. http://ci.athion.net/job/PlotSquared-Breaking/

**Comment by fhebuterne** [comment]
> Update to the latest plotsquared breaking build. http://ci.athion.net/job/PlotSquared-Breaking/
> 
> > <img alt="" width="48" src="/static/e24fd855/favicon.ico">**[PlotSquared-Breaking [Jenkins]](http://ci.athion.net/job/PlotSquared-Breaking/)**

Thanks, it's work perfectly !
