### ISSUE TITLE
[FAWE 1.14.4] //undo don't work and problem of permissions

### ISSUE THREAD

**Issue by Raphy123** [IntellectualSites/FastAsyncWorldEdit-1.13#250]
**[REQUIRED] FastAsyncWorldEdit Version Number: FastAsyncWorldEdit-1.14-99.jar** 

**[REQUIRED] Spigot/Paper Version Number: Paper 226 - 1.14.4** 

**Links to config.yml and config-legacy.yml file:** 

Config : https://pastebin.com/ieniw8YM
Config legacy https://pastebin.com/DQMqh8EG

**[REQUIRED] Description of the problem:**

First problem : //undo
The undo don't work : https://pastebin.com/Lh1QQ2kX

Second problem : OP can use worledit
When player use a //Cut for example, the command in chat is OK, but physically, nothing to change
For the chat, the action is DONE, but don't cut.

**Plugins being used on the server:**

https://athion.net/ISPaster/paste/view/9a95433109cb42d4a876565b7e82c26d

**How to replicate**:

1. Select area
2. //cut
3. //undo

1. Select area
2. //cut (with pack basic of permissions)

thank you

**Comment by MrAureliusR** [comment]
Seeing very similar problems, especially with //undo. It will often work the very first time after a reboot, but then it won't work after that. You can type //undo a million times and will never hit the "nothing left to undo" message.
We are also getting random bugs with //set and //replace, often extra blocks are added in unpredictable ways. A 3x3 selection that has //set stone used on it will end up with extra layers on top sometimes.
Debug Paste: https://athion.net/ISPaster/paste/view/c9f2ca9f3d1045d1bd1665961e977147
Config: https://pastebin.com/yVkNdj7L

**Comment by boy0001** [comment]
Try the latest version please.

**Comment by Raphy123** [comment]
Hi

Always the problem with permissions.
My player have permissions for use FAWE in plotsquared. //cut, msg appears in the tchat but nothing in the plot.
The problem is in my ticket
For admin, all works 
Thank you
