### ISSUE TITLE
Cant use Regen, I get an error code instead

### ISSUE THREAD

**Issue by Redcarred2** [IntellectualSites/FastAsyncWorldEdit-1.13#258]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

**[REQUIRED] Spigot/Paper Version Number:** 

[16:03:32 INFO]: FastAsyncWorldEdit-122 created by Empire92
[16:03:32 INFO]: &7FAWE version:
 - Date Nov 22, 2019 12:00:00 AM
 - Commit f123514a
 - Build 122
 - Platform bukkit
[16:03:32 INFO]: &7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[16:03:32 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.14-122;edcaeb6)

[16:03:32 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
**Links to config.yml and config-legacy.yml file:** 

https://pastebin.com/UeXcS8kf

**[REQUIRED] Description of the problem:**
I tried to use regen, then it popped up with an error, SOS

**Plugins being used on the server:**

**How to replicate**:

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Fixed in 97a4d2e10380ce2338da73fac9e1ef4d8a1b439b
