### ISSUE TITLE
.//fixlighting doesnt work

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#26]
It shows lighting propogated but nothing happens

using @IronApollo vector update

**Comment by AeSix** [comment]
Confirmed to still be an issue with FAWE-NVS 165

**Comment by KarlOfDuty** [comment]
Has any progress been made on this? It's a pretty big issue for us as we can barely use worldedit at all without this ruining the look of whatever we work on.

**Comment by MattBDev** [comment]
Lighting is more complicated than it seems. Minecraft has always had issues with lighting and although they have improved over time, plugins have a more difficult time getting it right. We understand the frustration.

**Comment by Tsoccerguy3** [comment]
Here is a temporary solution until the bug is fixed , after doing a lot of edits , run the plugin /cleanlight and it will fix all the lighting
https://github.com/bergerhealer/Light-Cleaner
it is also a good idea to fix the lighting on the map before you generate a dynmap

**Comment by KarlOfDuty** [comment]
I did try that for a bit a few months ago but it just shuffled the lighting issues around rather than solve them.

**Comment by Tsoccerguy3** [comment]
Use the Development builds from here
the 1.14.2 are for 1.13.2 as well
https://ci.mg-dev.eu/job/Light-Cleaner/

you must also use this dependency 
https://ci.mg-dev.eu/job/BKCommonLib/
