### ISSUE TITLE
Setting block entities will cause them to be invisible 

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/FastAsyncWorldEdit-1.13#260]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-1.14-132.jar

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-226 (MC: 1.14.4)

**Links to config.yml and config-legacy.yml file:** 
https://pastebin.com/XuhJEDjM
https://pastebin.com/6qLz3Ckh

**[REQUIRED] Description of the problem:**
Using FAWE to set a block entity such as a chest for example will be set as invisible:
![image](https://user-images.githubusercontent.com/10485646/69484745-d26f1080-0e2e-11ea-84d1-d9eff5d4e297.png)

**Plugins being used on the server:**
FastAsyncWorldEdit, WorldEdit, PlotSquared, PlugMan, SimpleAPI, SimplePets, BuycraftX, LuckPerms, LibsDisguises, ProtocolLib

**How to replicate**:
Select a region and do //set chest

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.13.2](https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
The chests become visible again if you relog.

**Comment by boy0001** [comment]
This is more or less, expected behavior. You are setting the block, but not any tile entities. If you set with the proper nbt it'll be fine. `//set chest{your nbt goes here}`
