### ISSUE TITLE
//walls returns -1 blocks changed

### ISSUE THREAD

**Issue by JordanPlayz158** [IntellectualSites/FastAsyncWorldEdit-1.13#267]
**[REQUIRED] FastAsyncWorldEdit Version Number: 141** 
https://athion.net/ISPaster/paste/view/7d4927b53e3446ed946a6ea019765bbc

[13:24:44 INFO]: &7FastAsyncWorldEdit-141 created by Empire92
[13:24:44 INFO]: &7FAWE version:
- Date Nov 24, 2019 12:00:00 AM
- Commit f16a6a1d
- Build 141
- Platform bukkit
[13:24:44 INFO]: &7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[13:24:44 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.14-141;e9595e3)
[13:24:44 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

**[REQUIRED] Spigot/Paper Version Number: 230** 
This server is running Paper version git-Paper-230 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-226 (MC: 1.14.4)
You are running the latest version

**[REQUIRED] Description of the problem: //walls doesn't do anything, it just shows output -1 blocks have been changed.**
No errors in console
 **[https://dl.fastermc.xyz/2019-11-24%2013-36-01.mkv](url)**
//walls doesn't work it just does nothing and shows -1 blocks have been changed
Who = Me
What = //walls
When = Today
Where = On my server
Why = it doesn't work
How = it doesn't change or add blocks and gives -1 blocks have been changed
Expected behavior = it makes a wall of the specified material with the selected blocks

**How to replicate**:
1. Get Paper.jar build 230 from https://papermc.io/api/v1/paper/1.14.4/230/download
2. Start the server
3. Download FAWE from https://intellectualsites.github.io/download/fawe.html under Spigot 1.14.4 dropdown.
4. Put FAWE in plugins folder.
5. Restart Server
6. Place 2 blocks
7. Select those 2 blocks
8. //walls <material>
9. Get output "-1 blocks have been changed."

**Plugins being used on the server:**
Plugins (17): ColorfulMix, Essentials, EssentialsSpawn, FastAsyncWorldEdit, HolographicDisplays, HungerGames, Multiverse-Core, NoteBlockAPI, PlaceholderAPI, ProtocolLib, ProtocolSupport, ProtocolTab*, Scoreboard-revision*, TooManyTrees, Vault, VoidGenerator, WorldEdit

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/34afc034433e3be1575ea4697b5453a56b7e2e62
