### ISSUE TITLE
/none does not unbind brush

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#27]
Bind a brush to an item
try to unbind the brush with /none

It says tool unbound, but the brush is still linked to the item

Using @IronApollo vector update

**Comment by RealmportalMC** [comment]
Edit you have to type /none twice for it to work

**Comment by SirYwell** [comment]
This may be related to the function to keep brushes when leaving the server. After re-joining, calling `/none` once will work fine.

**Comment by SirYwell** [comment]
Should be fixed in 39830046bc0c5150f709d11b504d77dbfad1a8a4.
