### ISSUE TITLE
SQL exception doing some commands

### ISSUE THREAD

**Issue by Artuto** [IntellectualSites/FastAsyncWorldEdit-1.13#270]
# Bug report for FastAsyncWorldEdit 1.14.4
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
```
>....=>.... [16:48:29 INFO]: &7FastAsyncWorldEdit-141 created by Empire92
>.... [16:48:29 INFO]: &7FAWE version:
- Date Nov 24, 2019, 12:00:00 AM
- Commit f16a6a1d
- Build 141
- Platform bukkit
>.... [16:48:29 INFO]: &7Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
>.... [16:48:29 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.14-141;e9595e3)
>.... [16:48:29 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

**[REQUIRED] Spigot/Paper Version Number:** 
`This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)`

**[REQUIRED] Description of the problem:**
Exception: https://hastebin.com/roqigoxeza.shell

**How to replicate**:
I was just doing some commands like //copy

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Can you try deleting your `history` folder ?

**Comment by Artuto** [comment]
That worked, thanks.
