### ISSUE TITLE
Commands not working for non-opped players

### ISSUE THREAD

**Issue by DoogiePC** [IntellectualSites/FastAsyncWorldEdit-1.13#272]
If a non-opped player tries a worldedit command on their plotsquared plot, it says it is running and doing it but no blocks actually place. Console shows this when using the command: https://hastebin.com/puzuxukugi.md

This is the /fawe debugpaste report: https://athion.net/ISPaster/paste/view/edf3c94aedd146719e1fbea7839220a7

Here is a screenshot of a player trying the command, they tried //set stone in front of them and nothing happened. https://i.imgur.com/fktxTdD.png

**Comment by N0tMyFaultOG** [comment]
Do not delete the template, also, use java 8.
