### ISSUE TITLE
Error on //set FAWE 1.14

### ISSUE THREAD

**Issue by ChimpGamer** [IntellectualSites/FastAsyncWorldEdit-1.13#279]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/a476ba2160d64920ab18990a5fc5154f (Also the url is not clickable when executing the command)

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
(FAWE) FastAsyncWorldEdit-152 created by Empire92
(FAWE) FAWE version:\n - Date Dec 3, 2019 12:00:00 AM\n - Commit fde28c94\n - Build 152\n - Platform bukkit
(FAWE) Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
(FAWE) ------------------ Platforms ------------------\n* Bukkit-Official(1.14-152;21d736c)\n
(FAWE) ---------------- Capabilities ----------------\nGAME_HOOKS: Bukkit-Official\nCONFIGURATION: Bukkit-Official\nUSER_COMMANDS: Bukkit-Official\nPERMISSIONS: Bukkit-Official\nWORLDEDIT_CUI: Bukkit-Official\nWORLD_EDITING: Bukkit-Official\n

**[REQUIRED] Spigot/Paper Version Number:** 

This server is running Paper version git-Paper-233 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Description of the problem:**

When executing //set <block> it throws this error: https://pastebin.com/gmdLZaC9. This user has no OP.

**How to replicate**:

**Plugins being used on the server:**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update Fawe, it works fine for me.
