### ISSUE TITLE
Some commands dont undo on //undo

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#28]
//caves //ore are a few ill keep updating the list as i find more.

using @IronApollo Vector update

**Comment by AeSix** [comment]
@RealmportalMC  have you found more operations that do not //undo properly/at all?

**Comment by Tsoccerguy3** [comment]
As of April 14 commits //undo is broken again on //rotate and //flip ,

**Comment by boy0001** [comment]
rotate and flip don't change any blocks.
