### ISSUE TITLE
FAWE and FAVS 1.13.2 compatibility (For a build server)

### ISSUE THREAD

**Issue by Piki-Studios** [IntellectualSites/FastAsyncWorldEdit-1.13#286]
# Bug report for FastAsyncWorldEdit 1.14.4

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 
https://athion.net/ISPaster/paste/view/bd6729f89210420fb81f8ec5fb0a983e

**[REQUIRED] FastAsyncWorldEdit Version Number:** 
FastAsyncWorldEdit-bukkit-1.13.208
FastAsyncVoxelSniper-1.14-16

**[REQUIRED] Spigot/Paper Version Number:** 
Paper-652.jar (1.13.2)

**[REQUIRED] Description of the problem:**
I see the above mentions using 1.14. However, we are using FAWE and FAVS with Arceon (1.13+) and goBrush (1.13) to run a build server. This means that we need the server to be a minimum of 1.13 to run the full FAWE/FAVS/Arceon/goBrush/goPaint suite. Also, 1.14 is stated as being unstable in both FAWE and FAVS for now. 

The problem we are having is FAVS as downloaded from the site (IS - set to 1.13.2) does not seem to be compatible with FAWE (1.13.2) running on Paper 1.13.2. I am getting a "Could not pass event PlayerJoinEvent" error on joining, and then an "IllegalAccessError" error when trying to use the arrow or gunpowder. 

I have noticed elsewhere on the internet that there are versions of FAVS and FAWE:
FastAsyncVoxelSniper-favs-1.13.135
FastAsyncWorldEdit-bukkit-1.13.135

Is there a FAVS 1.13.2 that is missing from Jenkins or the Downlaods page?

**How to replicate**:
Run a paper-652 (1.13.2) server with only FAWE and FAVS as downloaded from the main IS downloads page for Spigot version 1.13.2.

**Plugins being used on the server:**
FastAsyncWorldEdit-bukkit-1.13.208
FastAsyncVoxelSniper-1.14-16
As downloaded from the main IS Downloads page with 1.13.2 as the version setting

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [o] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Favs has been updated to match the latest Fawe changes a while ago. Make sure to update Fawe and Favs.
