### ISSUE TITLE
Masking Question

### ISSUE THREAD

**Issue by Lateralus46n2** [IntellectualSites/FastAsyncWorldEdit-1.13#296]
I have a question, when masking in 1.14.4 i noticed that you have to write each indiidual block and their their tag (ex. Jungle Wood = 17:3), where as in 1.12.2 you could just type log and  leaves and it would mask them two. Is there a way to do this now or no??!!!

**Comment by N0tMyFaultOG** [comment]
For questions move to our discord. This is an issue tracker.

**Comment by Lateralus46n2** [comment]
I cant i was banned for literally no reason at all. I tagged the devs, which after i was told you cant do that i said i wouldnt do it again. Then one of the admins decided to start an argument with me instead of helping me and ended up kick me because he was wrong. So i joined back and pasted my problem back in support, and didnt break any rules, then i was kicked again, i joined back and literally said nothing but "Why was a kicked again?" then i was banned. So, i have to resort to asking everything on here, is there anyother way i can contact you guys?

**Comment by N0tMyFaultOG** [comment]
Should've read the rules before tossing random pings 🤷‍♂
