### ISSUE TITLE
Rotate doesn't work with NBT data

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit-1.13#301]
If you rotate blocks with NBT data, e.g. chests, custom heads or signs, they will appear as invisible blocks and empty after pasting.

FAWE 1.15 - 13 
Paper 1.15.1 - 32

**Comment by TheoRetisch1** [comment]
Is this bug report invalid because of the missing template or because of the version 1.15.1?

**Comment by N0tMyFaultOG** [comment]
Think about why it prints you a template before deleting it.
