### ISSUE TITLE
Fawe half working on 1.13.2 (please read)

### ISSUE THREAD

**Issue by Firosee** [IntellectualSites/FastAsyncWorldEdit-1.13#325]
So, unlike versions before today, the plugin would not even load, however now it loads which is good! 

However i get these errors on startup: https://mcpaste.io/ec1dbfc4590ee8bf. Also, when in game, typing //wand, and or trying to execute worldedit commands, it shows this in chat, and does not execute the worldedit i did: https://gyazo.com/c846da831a491891a01f8e47d6af958b. This is the error it refers to in the console: https://mcpaste.io/485a8681504c7846. 

I really hope you can end up getting this working on 1.13.2, thank for for taking the time to look at this issue

**Comment by MattBDev** [comment]
we have dropped support for 1.13.2 due to a major bug that prevents the plugin from loading properly.  we haven't gotten to updating links and the project name yet.

**Comment by Firosee** [comment]
Does fawe currently work flawlessly on 1.14, or 1.15?

**Comment by MattBDev** [comment]
No.
