### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Nety01** [IntellectualSites/FastAsyncWorldEdit-1.13#326]
FAWE 1.15. Build 58
Paper 1.15.2 Build 85

I get this error on server startup https://hastebin.com/cunavodabe.md
Deleting DummyFawe.jar doesn't help

**Comment by datatags** [comment]
Same problem, also can't use any FAWE commands, but I get an error about it couldn't initialize BlockTypes.

**Comment by IronApollo** [comment]
FAWE does not currently support 1.15.2. This will be fixed in the near future. Sorry!
