### ISSUE TITLE
WorldEdit is totally broken in 1.15.2

### ISSUE THREAD

**Issue by CaoTrongThang** [IntellectualSites/FastAsyncWorldEdit-1.13#328]
Im using PaperSpigot 1.15.2
Previous version: git-Paper-83 (MC: 1.15.2)

FAWE version: FastAsyncWorldEdit-1.15-58
FAVS version: FastAsyncVoxelSniper-flattened-1.0.3-backward
FAWE config.yml: https://pastebin.com/BuhRpCwB

Im using //wand, //copy //paste as OP but no commands work and my builder using many commands of FAVS but sometimes blocks will disappear

Error when use //wand, //copy, //paste commands: https://pastebin.com

**Comment by Firosee** [comment]
Just thought i would say, that error you posted just leads to pastebin, not the actual error :)

**Comment by MattBDev** [comment]
Didn't follow the reporting format and provided wrong links to logs.
