### ISSUE TITLE
//paste -o does not pick proper location

### ISSUE THREAD

**Issue by adamlaughlin** [IntellectualSites/FastAsyncWorldEdit-1.13#36]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
Generate a 503 Interal Server error and Java exception from console; no result in game - no debug paste link

**Description of the problem:**

**How to replicate**:
I copied a selection and issued //schem -name-, then cleared clipboard and loaded it again to issue "//paste -o".  The clipboard was placed at [-16843174, 64, -16843088] instead of [-421, 64, -79].

**Comment by AeSix** [comment]
Using FAWE-NVS 165:
As schematics seem to not be working properly at all right now, this is difficult to test. 
However, I did copy a selection to clipboard, set the selection to air, moved and did //paste -a 
The object was replaced properly.   This issue will be testable again (and possibly fixed) when https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/68 is resolved.

**Comment by adamlaughlin** [comment]
I was actually referring to **-o** instead of **-a**.  -O is the flag for "original location" and allows me to use script driven paste events from the console.

**Comment by boy0001** [comment]
Cannot replicate. Assumed fixed.
