### ISSUE TITLE
//generate -h not making hollow and //generate data= does not append the data

### ISSUE THREAD

**Issue by RealJasomo** [IntellectualSites/FastAsyncWorldEdit-1.13#38]
Sorry debug paste also didn't work

**Comment by AeSix** [comment]
Possibly related to https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/32
I receive the same message in game for //generate as I do for //generatebiome

**Comment by N0tMyFaultOG** [comment]
Fixed in [e2c2205](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/e2c2205dac455ee14a3e58acc91b01737060bae6)
