### ISSUE TITLE
replace only sets

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/FastAsyncWorldEdit-1.13#41]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
https://incendo.org/paste/view/a41202a26874401b88642a764141e9d0

**Description of the problem:**

```//replace <old-block> <new-block>```
only sets the <old-block> to the selection
**How to replicate**:

put down random blocks, with stone being among them (or any block, it don't matter, stone is an example)
select the area
replace stone air
All blocks in the selection will become stone
(functions the same for every block I've tried)
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [] I made sure the bug/error is not caused by any other plugin

I'm fairly certain this is not another plugin, however if others are unable to reproduce, I will work on testing my setup more in-depth

**Comment by IronApollo** [comment]
#52
