### ISSUE TITLE
FAWE preventing Residence plugin from working properly

### ISSUE THREAD

**Issue by kaniesha** [IntellectualSites/FastAsyncWorldEdit-1.13#43]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**: https://hastebin.com/zeweditifo / https://pastebin.com/EF6wuDsF

**Description of the problem:**
+++ I'm sorry for the repost! I reposted this to FAWE 1.13 because I joined the discord and saw "legacy" and realized I posted my issue in the wrong place.
FastAsyncWorldEdit-bukkit-1.13.135.jar
With FAWE disabled, I am able to use this residence plugin linked below to expand and contract residences as it's meant to. With it enabled, I'm given a null error, which is the pastebin link. *The plugin link goes to my issue I left there. I'm hoping you may have some insight on how to solve the issue. If this is purely an issue with the other plugin, I apologize for the inconvenience!
https://github.com/Zrips/Residence/issues/263
https://pastebin.com/CtVpbBEC

**How to replicate**: Install residence, create a residence, attempt to use /res expand or /res contract.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Your issue is due to FAWE, in its current state, being based on a severely outdated version of WorldEdit. I am currently selectively distributing test versions of an updated FAWE specifically for compatibility checks. If you're interested in taking part in this testing process, please contact me via Discord, IronApollo#1953
