### ISSUE TITLE
Better Brushes not working anymore.

### ISSUE THREAD

**Issue by bidule995** [IntellectualSites/FastAsyncWorldEdit-1.13#45]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
https://hastebin.com/gawacavuxo

**Description of the problem:**
The Better Brushes plugin (Voxel Sniper addon) is not working anymore in 1.13 (no error message in the chat, it simply do nothing when right-clicking).

**How to replicate**:
- /b eb smooth
- /b eb lift
- /b eb fill
...

**Checklist**:
- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Better Brushes is either using an outdated API or is simply incompatible with FAVS. This won't be fixed by the FAWE team, and any updates regarding their compatibility should be given by the author of Better Brushes.

**Comment by bidule995** [comment]
Well it was fully compatible before the 1.13 update. Maybe you can add the Better Brushs features into FAVS. That's basically doing a /b bb at the same time as the erode brushs, for exemple /b eb fill will do /b bb and /b e fill at the same time.

**Comment by IronApollo** [comment]
I think I may have added that feature a month or so back when someone requested it. Let me know how it works in the updated FAVS when we release the compatibility update.
