### ISSUE TITLE
Right click with wand places offhand block

### ISSUE THREAD

**Issue by smellyonionman** [IntellectualSites/FastAsyncWorldEdit-1.13#58]
# Bug report for FastAsyncWorldEdit 1.13.x
**Description of the problem:**
Setting position 2 with mouse places blocks held in offhand.

**How to replicate**:
Hold any place-able block in offhand, wand in primary hand.  Set position 2 with a right click.  Block in offhand should place. 

**Checklist**:
*debugpaste not working at this time*

**Comment by AeSix** [comment]
This happens with the GreifPrevention inspection tool (stick) as well.  I'm not sure if there's a fix for this at the plugin level or if it requires a fix at the server level.

**Comment by RedstoneFuture** [comment]
I think FAWE can cancel the place-event at the same time with selections.
