### ISSUE TITLE
//mask don't work with leaves

### ISSUE THREAD

**Issue by Kaeios** [IntellectualSites/FastAsyncWorldEdit-1.13#59]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**: https://hastebin.com/icuqukugok

**Description of the problem:**

When you create a brush and set a mask, if you put id of leaves in the mask it is not replaced at all.

**How to replicate**:

1. Create a brush with **//br sphere air 10**
2. Apply leaves id (ex: spruce_leaves) to the mask with **//mask spruce_leaves**
3. Use the brush on spruce leave, it don't work.

**Checklist**:

- [X] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Aedesius** [comment]
I believe this has something to do with aliases and deprecated data values - "minecraft:spruce_leaves" works fine and affects all blocks, and in fact, "spruce_leaves" DOES work, but only on certain spruce leaves blocks.
