### ISSUE TITLE
Compilation Warnings

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#60]
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/0fa9d7a4a7a90160fc351a46a1f65fb44b98ecc8

@IronApollo Not sure if these warnings are something that should be addressed or not since compilation does complete successfully with an updated WorldGuard dependency, but I figured I'd forward this information to you anyways in case it is important to get resolved.

https://paste.ubuntu.com/p/S7SnzghFNY/

I'd assume the non-proprietary API warnings would be what's important.
i.e. https://paste.ubuntu.com/p/WZJxsZCdBP/

**Comment by MattBDev** [comment]
Won't fix. We will remove the proprietary API's eventually but not yet.
