### ISSUE TITLE
Masks >[ID] and <[ID] are negated

### ISSUE THREAD

**Issue by bidule995** [IntellectualSites/FastAsyncWorldEdit-1.13#61]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:

Issueception, I can't generate the debug paste, it freeze FAWE for few minutes and then send an error message.
![image](https://user-images.githubusercontent.com/16438002/53687207-1c104c00-3d32-11e9-8b19-5a3c053c56af.png)

**Description of the problem:**

The masks >[ID] and <[ID] are negated.
![image](https://user-images.githubusercontent.com/16438002/53687221-42ce8280-3d32-11e9-8c45-8f71d94bc7e3.png)

I need to negate them again to make them work.
![image](https://user-images.githubusercontent.com/16438002/53687228-537ef880-3d32-11e9-9663-debfe368bf94.png)

**How to replicate**:

For example to use /mask >[stone] --> I need to do /mask ![>[stone]].

**Checklist**:
- [] I included a `/fawe debugpaste` link
- [X] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
It's not only negated, but the behaviour is definitely broken

**Comment by boy0001** [comment]
Has since been fixed
