### ISSUE TITLE
AsyncWorld errors

### ISSUE THREAD

**Issue by Minkizz** [IntellectualSites/FastAsyncWorldEdit-1.13#64]
Hello, I get the following error when i'm trying to use "AsyncWorld"  @class:
https://pastebin.com/UZaGg6fs

**Comment by Minkizz** [comment]
I registered "WorldEdit" as a "depend" in plugin.yml, I added FAWE as external dependency in my workspace (Using Eclipse), it is NOT a dependency problem, thank you!

**Comment by Hwiggy** [comment]
I recommend putting both, because your plugin can still load before FAWE does, which would be the cause of this error.

**Comment by Sauilitired** [comment]
This is very much a dependency problem. The classes aren't available at runtime, meaning there's a missing dependency somewhere. 

Could you show us your `plugin.yml, @Minkizz?

**Comment by Minkizz** [comment]
@Sauilitired, my plugin.yml is:

`name: TalvorGames
version: 1.0
description: Core plugin for TalvorGames server.
author: Minkizz
main: com.talvorgames.minkizz.TalvorGames
api-version: 1.13
depend: [Votifier, PlaceholderAPI, WorldEdit, FastAsyncWorldEdit, SuperFriends]
commands:

  npc:
    description: Create NPCs.
    permission: talvorgames.command.npc

  broadcast:
    description: Broadcast a public message.
    aliases: [bc]
    permission: talvorgames.command.broadcast

  potatogun:
    description: Give yourself the potato gun!
    permission: talvorgames.command.potatogun

  lightningrod:
    description: Give yourself a lightning rod!
    permission: talvorgames.command.lightningrod

  tntcannon:
    description: Give yourself the TNT Cannon!
    aliases: [tntlaunch, tntlauncher]
    permission: talvorgames.command.tntcannon

  gamemode:
    description: Change a player gamemode.
    aliases: [gm]
    permission: talvorgames.command.gamemode

  gms:
    description: Change a player gamemode to Survival.
    permission: talvorgames.command.gms

  gmc:
    description: Change a player gamemode to Creative.
    permission: talvorgames.command.gmc

  gma:
    description: Change a player gamemode to Adventure.
    permission: talvorgames.command.gma

  gmsp:
    description: Change a player gamemode to Spectator.
    permission: talvorgames.command.gmsp

  home:
    description: Teleport to your home.
    aliases: [h]

  sethome:
    description: Set your home.
    aliases: [seth]

  vanish:
    description: Become invisible!
    aliases: [v, invis]
    permission: talvorgames.command.vanish

  reply:
    description: Reply to the latest player that you messaged.
    aliases: [r]

  mute:
    description: Mute or unmute a player.
    aliases: [m, silent]
    permission: talvorgames.command.mute

  randomteleport:
    description: Teleport randomly in Realistic Survival.
    aliases: [rtp, rteleport, wild, wilderness]

  server:
    description: Create your own server or join one!
    aliases: [s, host, hosting]

  command:
    description: Manage custom commands!
    aliases: [cmd]
    permission: talvorgames.command.command

  staffmeetup:
    aliases: [sm, smeetup]`

**Comment by MattBDev** [comment]
Could it be the order of the dependencies in the plugin.yml file that is causing the issue?  Try moving FAWE before WE

**Comment by Hwiggy** [comment]
Remove WorldEdit altogether and keep FAWE. Since WorldEdit is and always
will be a dependency of FAWE it does not make much sense to be redundant

**Comment by MattBDev** [comment]
Closing since we haven't heard back
