### ISSUE TITLE
water -> lava = Obsidian (on //set)

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/FastAsyncWorldEdit-1.13#66]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:

https://incendo.org/paste/view/e23eed25bf3d4adc8b63e874a3f41143
**Description of the problem:**

***This is not a duplicatable issue with WorldEdit 7 betas***
Water, when being set to lava generates obsidian in all of the area other than a few "holes" of lava.   
https://puu.sh/D2KdL/48ad032cd5.png
displaying that the surface layer is not the only layer affect:
https://puu.sh/D2Kgr/e9fc74d304.png
(the white outlines are the build-in CUI)

**How to replicate**:

Find or create an area of water.  (selected area, //set water)
select area within the water
do //set lava
watch as obsidian is generated in almost all of the water, except for a few single ~~blocks~~ *columns* of lava ~~at the top level~~, at the north west corner of (some of) the chunks and (sometimes) the area selection:
https://puu.sh/D2KnH/a2bee9adae.png 

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
This is also in affect regarding schematics, copy, paste, undo/redo: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/68

**Comment by N0tMyFaultOG** [comment]
Fixed in latest fawe-breaking
