### ISSUE TITLE
flowing water cut-off from source remains

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/FastAsyncWorldEdit-1.13#67]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:

https://incendo.org/paste/view/e23eed25bf3d4adc8b63e874a3f41143

**Description of the problem:**
 When setting stone (presumably all solid blocks) in a way which divides flowing water from it's source blocks, the flowing water remains.  

**How to replicate**:
 ***This issue is not applicable to WorldEdit 7 betas***
make a selection (any size should work - I did 7x7, 3 tall)
do //set water
Wait until the water starts to flow out
now do //walls stone

The flowing water remains, and acts similar to water source blocks.  
Additionally:
after doing //walls stone, do //walls lava (obsidian is generated as per https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/66 ) however, redoing //walls stone, the flowing water begins to be removed. 

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
If you place/break a block directly next to the flowing water does it stay or go away?

**Comment by Tsoccerguy3** [comment]
> 
> 
> If you place/break a block directly next to the flowing water does it stay or go away?

He may be describing a waterloged block such as a half slab or stair block or any other waterlogged block . they are easy to create but placing a block against them does not stop the water flow when the secondary block is broken. the water logged block needs to be broken to get rid of the flow of water

**Comment by AeSix** [comment]
I've had this issue with Spigot 1.13.2 - just the other day, actually. 
I *think* it may actually be somewhat of a Mojang issue.  I'm using WorldEdit (NOT FAWE) on this server (edge case reasons), where it happens to me.  So, not strictly an FAWE issue. 

So yeah.  I guess I kind of lied about it not being applicable to WE7 in my original post. 

Perhaps some more testing can be done, with WE7, FAWE, Spigot (without WE/FAWE, etc)

And @Tsoccerguy3 it *may* have something to do with waterlogged blocks, but I believe my original report was not in regards to those.  But hiik any more. lol
