### ISSUE TITLE
copy/paste/undo/redo/schematic (non-world block data storage?) issue(s) 

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/FastAsyncWorldEdit-1.13#68]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
 https://incendo.org/paste/view/e23eed25bf3d4adc8b63e874a3f41143

**Description of the problem:**
 Creating schematics is broken.  More specifically, /schem list  is broken, does not show any schematics.  Pasting schematics is broken, as it will paste random data. Copy and Paste is broken when using RAM.

First test (new configs):
disk / lvl 1
copy & paste: pastes object as is copied.
schem paste: Pastes random blocks or no blocks/air 
undo & redo: seemingly works properly

Subsequent tests in this order:
disk / lvl 0 -
copy & paste: pastes the object as copied. No alterations.
schem paste: fails to paste schematic properly (or at all)
undo & redo: seemingly works properly

RAM / lvl 0 - 
copy & paste: does not paste the same object. See images below.
schem paste: same as disk/lvl0
undo & redo: Does not clean up certain blocks from the paste when doing //undo - however, going one more //undo and then a //redo puts the object in it's expected state
https://puu.sh/D2NT0/da524b8b44.png  (object to be copied)
https://puu.sh/D2NTH/e228b6c9fa.png (object pasted from clipboard over original)
https://puu.sh/D2NUv/c87eca0b9f.png (object pasted in same location after //set air)
https://puu.sh/D2O0N/de4e18fa6c.png (failed //undo after paste)

RAM / lvl 1 -
copy & paste: same as lvl 0
schem paste: same as disk/lvl0
undo & redo: same as RAM/lvl 0

In summary:
RAM has issues with the clipboard and copy/paste (Perhaps it's pasting exactly what is stored, but failing to save the correct data for what is copied?)
Disk copy/paste seems to work perfectly fine.
RAM & Disk have major issues with schematic saving and pasting. Again, perhaps this is an issue with writing the copied data as opposed to reading from storage or writing to world. 
/schem list does not show any schematics listed - per-player set to true or false.

**How to replicate**:
 First, I started with using my configs.  This proved to give the same results as described above.  Then I removed my FAWE config (renamed the entire folder) and allowed to generate a new set of configs.  Same results. 

Changing clipboard settings (disk/ram and compression):  
(to be updated)

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
related issue
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/56

**Comment by AeSix** [comment]
#75 & #56 are related.

**Comment by xion87** [comment]
you have to use "//Schematic list all" for show all schematics

**Comment by AeSix** [comment]
I confirm, //schem list all  does show a list of schematics.
However, when per-player schematics are fall, this should not be needed.

**Comment by Tsoccerguy3** [comment]
//schem load or //schematic load of large schematics causes java exception and results in java error  and statement ,TO BE FIXED

**Comment by AeSix** [comment]
@Tsoccerguy3  Perhaps yelling at the volunteers who are already spending a good portion of their free time working on this code is not the best way to get issues resolved. 

What happens if you increase -Xnx to a higher amount, still the same for those schems?

**Comment by Tsoccerguy3** [comment]
increased max memory from 2 GIG to 4 GIG 

 Just Tested a massive schematic 6 megs of a mini world map from PMC .

Load , No problem
Paste , No problem
Undo , No problem , if the paste was out side an area that had not generated chunks yet , the undo left a few blocks high up in the air
Redo , No problem
Undo , No problem

Testing these commands , working ok ,
