### ISSUE TITLE
Proposition: Remove PlotMe support

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualSites/FastAsyncWorldEdit-1.13#69]
A proposition to remove the PlotMe "Feature" was brought up in the Discord by MattBDev. PlotMe has not been supported since ~MC 1.8. It is certain it will not work on 1.13+ and will be of no use in FAWE-1.13 and moving forward.

**Comment by AeSix** [comment]
It does indeed make more sense to remove PlotMe stuff from FAWE for 1.13+ - 
however, leaving it in legacy (if it gets updates at all) is probably better as it would be a waste of time to do so, and it may still work in some circumstances.

**Comment by Sauilitired** [comment]
I agree with what Ae said. The PlotMe conversion code also removed from 1.13 PlotSquared because of the same reason. It's pretty safe to say that PlotMe isn't going to be updated.

**Comment by MattBDev** [comment]
@Sauilitired it won't be updated unless someone forks the project which I hope no one will do.

**Comment by N0tMyFaultOG** [comment]
Removed in https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/pull/79
