### ISSUE TITLE
NBT data lost on item duplication (signs, chests, banners, heads, etc)

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/FastAsyncWorldEdit-1.13#71]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
 https://incendo.org/paste/view/47dc86e300b24c2c8f744cdd0388742b

**Description of the problem:**
 Items with NBT data do not carry over the NBT data (standard worldedit issue for new minecraft versions) 
Signs (copy, rotation, stack, etc - but no text)
Chests (chest copies, but is empty)
Banners (standard copy, customized ones paste base banner only)
heads (revert to basic skull)

**How to replicate**:
  Place item, select then perform any number of actions to cause a duplicate item to be created (//stack; //copy & //paste; etc)

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
For me, sometimes chests work but other times they don't.

**Comment by AeSix** [comment]
I just realized I created a more detailed duplicate, orignal here:
https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/25

**Comment by dextonanderson** [comment]
Can confirm. Works with stock WE 7. FAWE-1.13-NVS does not. I have never been able to even sometimes get chests to work. NBT is just not implemented somewhere?

**Comment by Sauilitired** [comment]
Can also confirm. I'll close the other issue, as it's superseded by this.

**Comment by IronApollo** [comment]
Please test this issue with 3236bdd78eb07fb3fc1de7dea608ebeb29b6f6cf and update the issue, Thanks!

**Comment by TheoRetisch1** [comment]
I can confirm this problem for the process of rotating/flipping heads, chests, signs and banners.

The test was done using a newly generated config and a newly generated DUMMY file.
FAWE 1.13.176
Paper 1.13.2 - 641
