### ISSUE TITLE
Crash on //set red_concrete_powder

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/FastAsyncWorldEdit-1.13#72]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
 (from about half an hour previous to this) 
https://incendo.org/paste/view/8f1a5635577e447b9aa49fdeab02bc25

**Description of the problem:**
 upon doing "//set red_concrete_powder" the server began to crash. Hard.  Here's the log; It starts at 21:33:53 
https://termbin.com/muer

**How to replicate**:

select a large area (my area is 200x200 1 tall)
(I first had set sand, then anvils (testing another issue), then grass before the powder - the first three set OK, sand and anvils fell, grass did not nor did it break.)
do //set red_concrete_powder
Other powders may cause this as well.

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Tsoccerguy3** [comment]
selected area 300 x 300 
//set red_concrete_powder

Tested lastest build , no longer crashes , problem fixed


Please close
