### ISSUE TITLE
Mounted schematic are not detected by fawe (but yes if using WE)

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/FastAsyncWorldEdit-1.13#75]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**: 
https://hastebin.com/utujeruyuv

**Description of the problem:**
Basicall i have a folder that is accesible by all server (i am using pterodapyl panel) the folder is called "/schematics" (with slash)
If i use it on normal we i type this on config:
saving:
    dir: /schematics
and i have access to all schematic saved and i can save here
Instead with fawe if i use the same config on "config-legacy.yml"
saving:
    dir: /schematics
It keep to save schematic and stuff on the classic schematic folder

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
@xion87 in #68 you said (and I confirmed) that //schem list all shows the global schematics. 
Does this work for you, or not at all?

**Comment by xion87** [comment]
it don't work by using that virtual folder, instead it work with WE

**Comment by AeSix** [comment]
Ok.  I had a similar setup - to share schems between my creative server and parkours server.  I believe I had to do "../../../../../schematics/" - it was annoying, but worked.  FAWE used the plugins/FastAsyncWorldEdit/ directory as base.  

Try adding a trailing /  (so, "/schematics/")
And if that fails, try the ../../../ method.

This might help Iron figure out what it's doing badly :)

I'll see about testing my setup as well, but I have to do it when no staff are on as they will likely try to move parkours... which schematics are rather broken, and... yeah. Staff don't pay attention :,(

**Comment by xion87** [comment]
basicall that url is the docker url that redirect the folder to another server (that i use it as main storage for schematics)
                    HostConfig: {
                        Mounts: [
                            {
                                Target: '/home/container',
                                Source: this.server.path(),
                                Type: 'bind',
                                ReadOnly: false,
                            },
                            {
                                Target: Config.get('docker.timezone_path'),
                                Source: Config.get('docker.timezone_path'),
                                Type: 'bind',
                                ReadOnly: true,
                            },
                            {
                                Target: '/schematics',
                                Source: '/home/83ac2e3c-6408-4e77-8a1d-e66ea0b3f006/plugins/WorldEdit/schematics',
                                Type: 'bind',
                                ReadOnly: false,
                            },
                            {
                                Target: '/pixelmon',
                                Source: '/home/577534cc-a66f-48ca-81b8-90ac056b362b/world',
                                Type: 'bind',
                                ReadOnly: false,
                            },
                            {
                                Target: '/turfwars',
                                Source: '/home/24162b24-fff8-4d1c-ac63-b84fd985715a/plugins/TurfWars/players',
                                Type: 'bind',
                                ReadOnly: false,
                            },
                        ],

**Comment by AeSix** [comment]
ok.  Docket makes this a lot more complicated I think.

From within plugins/FastAsyncWorldEdit/ can you do:
ls /schematics
and see the contents?

**Comment by xion87** [comment]
nvm for any strange reason is working, i was using the command without all so it don't show things xD
