### ISSUE TITLE
flip stairs results in random stair direction

### ISSUE THREAD

**Issue by Tsoccerguy3** [IntellectualSites/FastAsyncWorldEdit-1.13#77]
Im confused , some people say //flip is fixed in the latest version pulled from Jenkins FastAsyncWorldEdit-bukkit-1.13.135

Stairs are definitely not flipped correctly
 
![2019-03-22_19 11 47](https://user-images.githubusercontent.com/22108822/54858224-ef6ca600-4cd9-11e9-95eb-94ac7a4c263d.png)
![2019-03-22_19 12 02](https://user-images.githubusercontent.com/22108822/54858226-ef6ca600-4cd9-11e9-9af6-30aac58c7d7d.png)

**Comment by SirYwell** [comment]
Rotating and flipping isn't fixed in that build. In the newest dev build, it seems to be fixed.

**Comment by Tsoccerguy3** [comment]
Could you post a link to the latest commit where rotation and flip work and ill compile that .

Thank you

**Comment by SirYwell** [comment]
Try to build from the [new-vector-system](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/tree/new-vector-system) branch or download it [here](https://cdn.discordapp.com/attachments/394318266987839509/557751285151957003/FastAsyncWorldEdit-bukkit-1.13.165.jar). If you still have Trouble with rotating or flipping, please comment on #23 to keep things clean

**Comment by Tsoccerguy3** [comment]
moved results to https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/23#issuecomment-475904615

**Comment by Tsoccerguy3** [comment]
More testing with //flip , I do not think the problem is related to //rotate as that is fixed .
More findings posted in https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues/23#issuecomment-475904615

**Comment by Tsoccerguy3** [comment]
As you can see in the pictures , After a //flip the corner stairs have wrong ID's used , Matt if you can locate the code for this and replace the wrong Stair Corner ID's with the correct ones . Thank You

![2019-03-28_19 34 47](https://user-images.githubusercontent.com/22108822/55199614-fc354200-5190-11e9-9a6e-0e479ca800e9.png)
![2019-03-28_19 35 06](https://user-images.githubusercontent.com/22108822/55199615-fc354200-5190-11e9-8a05-f5e9c7bc408a.png)
![2019-03-28_19 35 15](https://user-images.githubusercontent.com/22108822/55199616-fc354200-5190-11e9-977d-2c8dabfc13b3.png)
![2019-03-28_19 35 26](https://user-images.githubusercontent.com/22108822/55199617-fc354200-5190-11e9-98cf-59a994e89a71.png)

**Comment by Tsoccerguy3** [comment]
Has anyone , had any success in fixing the corner stair flip bug ,?

**Comment by Tsoccerguy3** [comment]
//flip while facing north , then pasting  does nothing or does a partial paste  ,  problem almost fixed

**Comment by boy0001** [comment]
@Tsoccerguy3 Can't replicate. Can you give me steps to reproduce? e.g. what block / orientation.
(doing `//distr -d` can tell you the block state you have selected)

**Comment by Tsoccerguy3** [comment]
lay random stair types in a 3 x 3 square .
select pos1 and pos2 of the 3 x 3 stair pattern
stand outside the pattern , on east side and //copy , then looking east //flip , then paste
no need to do a select again , since the selection is already done
move to each of the sides of the 3 x 3 pattern and //copy , then //flip , then //paste to the direction you are facing
you will find when you are on the the north side that operations get messed up , maybe its the clipboard

it does not happen if i do a new selection each time before i do a copy

**Comment by Tsoccerguy3** [comment]
Issue Fixed and closing
