### ISSUE TITLE
Performance regression and random chunk pasting.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#81]
Paper dev (Spigot 1.13.2)
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e (3/25 compile).

There seems to be quite a performance regression with FAWE 1.13 compared to FAWE 1.12. Previously you could do ~100 million edits without TPS so much as flinching and fairly fast too. Now, FAWE seems to struggle a bit with relatively saner numbers.

This is with a 1.8 million & 4.1 million operation.
https://cdn.discordapp.com/attachments/119102811421147138/559912421322522658/2019-03-26-01-21-00.gif

Chunks also seem to sporadically be operated on instead of in any linear direction. Not sure if intended.

Using default FAWE settings with relighting and tick-limiter disabled (due to the broken state of them). 
https://paste.ubuntu.com/p/Rf22qFttgw/

**Comment by MattBDev** [comment]
The commit version is irrelevant to this issue. 1.13 did cause a major slowdown due to the number of changes in the Bukkit API.

**Comment by MattBDev** [comment]
Fixed in 712479a

**Comment by mibby** [comment]
Commit version may be irrelevant to the issue in general, but I figured it's good practice to at least let you know what version of FAWE it was tested on for future possible optimizations and testing. :(

**Comment by MattBDev** [comment]
@mibby I didn't mean to close this issue, I meant to close the other one you opened since I fixed it. The issue will be looked at as soon was we can put out a stable release.

**Comment by boy0001** [comment]
> Chunks also seem to sporadically be operated on instead of in any linear direction. Not sure if intended.

It was always sporadic, just wasn't noticeable before since it was faster.

**Comment by boy0001** [comment]
Fixed
