### ISSUE TITLE
Entities are not loaded from nbt schematics

### ISSUE THREAD

**Issue by weaondara** [IntellectualSites/FastAsyncWorldEdit-1.13#88]
# Bug report for FastAsyncWorldEdit 1.13.x
Fawe version: nvs branch: c820406e8c8f3680f92b9fd2e22ded3ae3ac431c merged with master 603df92f79b0e189a7e3acec7db6bf2aa0fe2940
**Debug paste link**:
excluded for privacy reasons
**Description of the problem:**
Enities are not loaded when loading an nbt schematic. We were able to find out that entities seem to be saved by opening the save schematic with an nbt editor. So our prediction is that most likely the entities are not loaded from the nbt schematic file. Copying and pasting works but copy->save->load->paste does not.

**How to replicate**:
- copy selection with entities in it e.g. armor stands
- save chematic //sem save structure file
- load schematic again
- paste

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by weaondara** [comment]
oh yeah my fault thx

**Comment by boy0001** [comment]
Thanks, fixed.
