### ISSUE TITLE
Clipboard on disk: entities and nbt data of blocks not saved

### ISSUE THREAD

**Issue by weaondara** [IntellectualSites/FastAsyncWorldEdit-1.13#90]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:
https://incendo.org/paste/view/f880040002194b96a6970bb2518b9966

**Description of the problem:**
Entities and nbt data of blocks is not save in the clipboard on disk

**How to replicate**:
Copy a selection with entities and/or chests, signs, etc. 
Disconnect from server
Connect again
Paste

**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by mibby** [comment]
I also experience this, however it's when trying to use a 1.12 FAWE schematic in a 1.13 FAWE environment. Using WorldEdit to transfer chests with various contents & NBT data, as well as custom heads, they end up pasted without all of their corresponding data.

(New Server on 1.13.2)
Paper dev 597 (Spigot 1.13.2)
FAWE 1.13 dev 141

(Old Server on 1.12.2)
Paper dev 1611(Spigot 1.12.2)
FAWE dev 1257

* Go into old server (1.12), make a selection around build/chests, copy to clipboard, save as schematic.
* Upload schematic to new server.
* Attempt to paste schematic in new server (1.13), all the NBT data is missing.

**Comment by weaondara** [comment]
i'm not talking about schematics, i'm talking about the clipboard on disk ... the .bd files

**Comment by mibby** [comment]
It's probably all part of the same logic that interprets the written NBT data, no? Seeing as schematics are partially broken as well with NBT data pasting, it's not _that bad_ to inform that it's broken logic in a relevant ticket.

**Comment by weaondara** [comment]
not sure if that's the same
the schematics do work btw includeing entites and chest, signs, ...

**Comment by weaondara** [comment]
bump @N0tMyFaultOG complete now

**Comment by boy0001** [comment]
yeah, the serialization isn't implemented yet.

**Comment by weaondara** [comment]
ok, I guess that's a feature request then
