### ISSUE TITLE
Current builds of FAWE not compilling on Linux Mint 19.1 

### ISSUE THREAD

**Issue by Tsoccerguy3** [IntellectualSites/FastAsyncWorldEdit-1.13#92]
**Description of the problem:**

Linux does not like compiling in shared protected memory from command-line , as in running from a script . got 100 of these errors and 7 warnings . Eclipse can deal with this .

/home/wds/dev/fawe/worldedit-core/src/main/java/net/jpountz/util/UnsafeUtils.java:39: warning: Unsafe is internal proprietary API and may be removed in a future release
            UNSAFE = (Unsafe) theUnsafe.get(null);

**How to replicate**:

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by SirYwell** [comment]
If you can't compile due to this, you probably need to adjust your compiler parameters. If you need further help, please send a complete log.

**Comment by Tsoccerguy3** [comment]
wds@wds-GP72-6QF:~/dev/fawe$ ./gradlew build

> Configure project :
 
============= You are compiling: =============
 _______    ___   ____    __    ____  _______
|   ____|  /   \  \   \  /  \  /   / |   ____|
|  |__    /  ^  \  \   \/    \/   /  |  |__
|   __|  /  /_\  \  \            /   |   __|
|  |    /  _____  \  \    /\    /    |  |____
|__|   /__/     \__\  \__/  \__/     |_______|

======= By Empire92 and WorldEdit team =======

If you encounter trouble:
 - Run `build` in a separate Gradle run
 - Use gradlew and not gradle
 - Ask us!
   - https://discord.gg/ngZCzbU (Discord)

Files will be output to `/target`

==============================================


> Task :worldedit-core:compileJava
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils9.java:3: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils.java:15: warning: ConstructorAccessor is internal proprietary API and may be removed in a future release
import sun.reflect.ConstructorAccessor;
                  ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils.java:16: warning: FieldAccessor is internal proprietary API and may be removed in a future release
import sun.reflect.FieldAccessor;
                  ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils.java:17: warning: ReflectionFactory is internal proprietary API and may be removed in a future release
import sun.reflect.ReflectionFactory;
                  ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/JSystemFileChooser.java:10: warning: FilePane is internal proprietary API and may be removed in a future release
import sun.swing.FilePane;
                ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/BrowseButton.java:7: error: package javafx.application does not exist
import javafx.application.Platform;
                         ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/BrowseButton.java:8: error: package javafx.embed.swing does not exist
import javafx.embed.swing.JFXPanel;
                         ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/BrowseButton.java:9: error: package javafx.stage does not exist
import javafx.stage.DirectoryChooser;
                   ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/object/io/zstd/UnsafeUtil.java:30: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/object/io/zstd/ZstdFrameDecompressor.java:24: warning: Unsafe is internal proprietary API and may be removed in a future release
import static sun.misc.Unsafe.ARRAY_BYTE_BASE_OFFSET;
                      ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/object/io/zstd/FiniteStateEntropy.java:19: warning: Unsafe is internal proprietary API and may be removed in a future release
import static sun.misc.Unsafe.ARRAY_BYTE_BASE_OFFSET;
                      ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/object/io/zstd/ZstdDecompressor.java:35: warning: Unsafe is internal proprietary API and may be removed in a future release
import static sun.misc.Unsafe.ARRAY_BYTE_BASE_OFFSET;
                      ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/Fawe.java:89: error: cannot find symbol
    private BStats stats;
            ^
  symbol:   class BStats
  location: class Fawe
/home/wds/dev/fawe/worldedit-core/src/main/java/com/sk89q/util/ReflectionUtil.java:22: warning: ConstructorAccessor is internal proprietary API and may be removed in a future release
import sun.reflect.ConstructorAccessor;
                  ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/sk89q/util/ReflectionUtil.java:23: warning: FieldAccessor is internal proprietary API and may be removed in a future release
import sun.reflect.FieldAccessor;
                  ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/sk89q/util/ReflectionUtil.java:24: warning: ReflectionFactory is internal proprietary API and may be removed in a future release
import sun.reflect.ReflectionFactory;
                  ^
/home/wds/dev/fawe/worldedit-core/src/main/java/net/jpountz/util/UnsafeUtils.java:19: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/BrushCache.java:97: warning: non-varargs call of varargs method with inexact argument type for last parameter;
            displayMap.put("Lore", FaweCache.asTag(json.split("\\r?\\n")));
                                                             ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils9.java:86: warning: Unsafe is internal proprietary API and may be removed in a future release
        Constructor<?> constructor = Unsafe.class.getDeclaredConstructors()[0];
                                     ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils9.java:88: warning: Unsafe is internal proprietary API and may be removed in a future release
        Unsafe unsafe = (Unsafe) constructor.newInstance();
        ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils9.java:88: warning: Unsafe is internal proprietary API and may be removed in a future release
        Unsafe unsafe = (Unsafe) constructor.newInstance();
                         ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils.java:133: warning: ConstructorAccessor is internal proprietary API and may be removed in a future release
    private static ConstructorAccessor getConstructorAccessor(Class<?> enumClass,
                   ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils.java:140: warning: ReflectionFactory is internal proprietary API and may be removed in a future release
        return ReflectionFactory.getReflectionFactory().newConstructorAccessor(enumClass.getDeclaredConstructor(parameterTypes));
               ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils.java:163: warning: FieldAccessor is internal proprietary API and may be removed in a future release
            FieldAccessor fa = ReflectionFactory.getReflectionFactory().newFieldAccessor(field, false);
            ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/util/ReflectionUtils.java:163: warning: ReflectionFactory is internal proprietary API and may be removed in a future release
            FieldAccessor fa = ReflectionFactory.getReflectionFactory().newFieldAccessor(field, false);
                               ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/JSystemFileChooser.java:25: warning: FilePane is internal proprietary API and may be removed in a future release
            FilePane filePane = findFilePane(this);
            ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/JSystemFileChooser.java:26: warning: FilePane is internal proprietary API and may be removed in a future release
            filePane.setViewType(FilePane.VIEWTYPE_DETAILS);
                                 ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/JSystemFileChooser.java:27: warning: FilePane is internal proprietary API and may be removed in a future release
            filePane.setViewType(FilePane.VIEWTYPE_LIST);
                                 ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/JSystemFileChooser.java:42: warning: FilePane is internal proprietary API and may be removed in a future release
    private static FilePane findFilePane(Container parent){
                   ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/JSystemFileChooser.java:44: warning: FilePane is internal proprietary API and may be removed in a future release
            if(FilePane.class.isInstance(comp)){
               ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/JSystemFileChooser.java:45: warning: FilePane is internal proprietary API and may be removed in a future release
                return (FilePane)comp;
                        ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/JSystemFileChooser.java:50: warning: FilePane is internal proprietary API and may be removed in a future release
                    FilePane found = findFilePane(cont);
                    ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/BrowseButton.java:30: error: cannot find symbol
        DirectoryChooser folderChooser = new DirectoryChooser();
        ^
  symbol:   class DirectoryChooser
  location: class BrowseButton
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/BrowseButton.java:30: error: cannot find symbol
        DirectoryChooser folderChooser = new DirectoryChooser();
                                             ^
  symbol:   class DirectoryChooser
  location: class BrowseButton
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/BrowseButton.java:33: error: cannot find symbol
        new JFXPanel(); // Init JFX Platform
            ^
  symbol:   class JFXPanel
  location: class BrowseButton
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/installer/BrowseButton.java:34: error: cannot find symbol
        Platform.runLater(() -> {
        ^
  symbol:   variable Platform
  location: class BrowseButton
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/object/io/zstd/UnsafeUtil.java:37: warning: Unsafe is internal proprietary API and may be removed in a future release
    public static final Unsafe UNSAFE;
                        ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/object/io/zstd/UnsafeUtil.java:44: warning: Unsafe is internal proprietary API and may be removed in a future release
            Field theUnsafe = Unsafe.class.getDeclaredField("theUnsafe");
                              ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/object/io/zstd/UnsafeUtil.java:46: warning: Unsafe is internal proprietary API and may be removed in a future release
            UNSAFE = (Unsafe) theUnsafe.get(null);
                      ^
/home/wds/dev/fawe/worldedit-core/src/main/java/com/boydti/fawe/Fawe.java:171: error: cannot find symbol
                this.stats = new BStats();
                                 ^
  symbol:   class BStats
  location: class Fawe
/home/wds/dev/fawe/worldedit-core/src/main/java/net/jpountz/util/UnsafeUtils.java:27: warning: Unsafe is internal proprietary API and may be removed in a future release
    private static final Unsafe UNSAFE;
                         ^
/home/wds/dev/fawe/worldedit-core/src/main/java/net/jpountz/util/UnsafeUtils.java:37: warning: Unsafe is internal proprietary API and may be removed in a future release
            Field theUnsafe = Unsafe.class.getDeclaredField("theUnsafe");
                              ^
/home/wds/dev/fawe/worldedit-core/src/main/java/net/jpountz/util/UnsafeUtils.java:39: warning: Unsafe is internal proprietary API and may be removed in a future release
            UNSAFE = (Unsafe) theUnsafe.get(null);
                      ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors
34 warnings

> Task :worldedit-core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':worldedit-core:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by MattBDev** [comment]
You need to install the JavaFX library. As for the unsafe stuff.... you don't need to worry about that.

**Comment by boy0001** [comment]
Try only building the modules you want e.g.
`gradlew :worldedit-bukkit:build`
