### ISSUE TITLE
//undo .//cut and probably other commands not functioning correctly.

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/FastAsyncWorldEdit-1.13#94]
**Debug paste link**:
https://incendo.org/paste/view/389272fd36274ecfa417b9bf3d4a3e85

**Description of the problem:**

I typed in //cut after making a selection. nothing happens, although it says x blocks cut.
I then tried //replace air. it said X blocks replaced, but nothing changed.
And finally, i did //set stone and went to //undo, it just removed the blocks from the prior edit instead of restoring them.

**How to replicate**:
1: select something that contains blocks. 
2: change the blocks with either //set //replace etc. 
3: type //undo.
4: The blocks should dissapear instead of being restored.
 
**Checklist**:

- [x] I included a `/fawe debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by Tsoccerguy3** [comment]
check and see if you have World-edit in your plugin folder , you can not have FAWE and World-edit together . also you will get this effect if plot-squared is installed

**Comment by RealmportalMC** [comment]
> 
> 
> check and see if you have World-edit in your plugin folder , you can not have FAWE and World-edit together . also you will get this effect if plot-squared is installed

I assumed that FAWE would work with p2 because of MattBDev comment on discord.

**Comment by Tsoccerguy3** [comment]
I just compiled the master and tested //cut , //undo  and //paste .working now . //schematic load seems to load , but //pasting does not paste the entire schematic .  //flip does not work with stair corners

**Comment by PhanaticD** [comment]
I am having this issue too: 

copy on this: https://gyazo.com/abb04b1385ff0a79f24143b213d57b2d

do //paste and get this: https://gyazo.com/f7dadd3894fa7d7f1b71c3a0e65730a5

**Comment by Tsoccerguy3** [comment]
wait till breaking and master are merged , i had that problem //pasting a schematic .

**Comment by Tsoccerguy3** [comment]
Working as of last commit , please close
