### ISSUE TITLE
WorldGuard loading before FAWE 1.13

### ISSUE THREAD

**Issue by mrcoffee1026** [IntellectualSites/FastAsyncWorldEdit-1.13#97]
# Bug report for FastAsyncWorldEdit 1.13.x

**Debug paste link**:

https://incendo.org/paste/view/01e11947f8724e49953c0aeb8f026cf1

**Description of the problem:**
This is issue #47 again.  While this WAS confirmed fixed before this exists again in every version of FAWE from build #141 onward (at least.. I haven't tried builds prior to this).  combined with all versions of WorldGuard latest dev build 1835 as well as latest "stable" -beta3.

**How to replicate**:
You might also need worldguardExtraFlags installed to replicate, though I'm not certain of this.  original poster had this, I have this... other people seem to be running without this error?

Won't show in debugpaste since this omits chunks of latest.log where the error appears (https://pastebin.com/H3eB0Hy6)

**Checklist**:

- [] I included a `/fawe debugpaste` link
- [] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of [FAWE for 1.13.x](https://ci.athion.net/job/FAWE-1.13/)
- [] I made sure the bug/error is not caused by any other plugin

**Comment by mibby** [comment]
Can't reproduce. The plugin.yml changes fixed the issue for me.

Paper dev 603 (Spigot 1.13.2)
FastAsyncWorldEdit-1.13 dev 147
WorldGuard dev 1830
WorldGuardExtraFlags dev 16
PlotSquared-Breaking dev 214

Also tested FastAsyncWorldEdit-Breaking dev 2.

**Comment by mrcoffee1026** [comment]
Do I have to manually modify the plugin.yml inside the jar itself every single time I want to update then?  This problem persists with the versions you've specified here.

**Comment by mrcoffee1026** [comment]
In the current plugin.yml, softdepend setting is commented out which I guess doesn't override the hardcoded (?) setting that puts WorldGuard in that list and so this issue persists.

**Comment by mibby** [comment]
Test with actual dev build version downloads, not generic download links with no version specified. The logs you provided do not indicate you tested with newer versions. Nor should you really be targeting use of dev builds with outdated dependencies. If you require stable releases, wait for publication on bukkit/spigot release channels.

https://papermc.io/ci/view/all/job/Paper-1.13/
http://ci.athion.net/job/FastAsyncWorldEdit-1.13/
http://builds.enginehub.org/job/worldguard?branch=master
https://jenkins.isokissa3.fi/job/WorldGuardExtraFlags/changes
http://ci.athion.net/job/PlotSquared-Breaking/

http://ci.athion.net/job/FastAsyncWorldEdit-Breaking/changes

Do _not_ use WorldGuard dev builds 1831+ with FAWE as it relies on an upstream breaking change in WorldEdit that is _not_ currently present in FAWE. As well as make sure you aren't running multiple different versions of plugins at the same time or have some plugin forcing WorldGuard to load early.

As previously mentioned; with the changes boy0001 made to FAWE's plugin.yml, FAWE properly initializes before WorldGuard and as the first plugin in the startup sequence inside a heavy plugin production environment (104 plugins in use). This is also interchangeable with using upstream WorldEdit -- where an unmodified WorldEdit initializes fine, just as an unmodified latest dev of FAWE initializes fine.

If you require use of older dependencies that force WorldGuard to load before, then yes, I'd presume you would have to modify the plugin.yml every time you wish to use a newer dev build.

**Comment by mibby** [comment]
I also noticed you are using AreaShop. AreaShops is _not_ currently compatible with FAWE 1.13. Neither the public release or the latest dev builds.

You can however compile the latest source of AreaShops with _all_ dependency modules removed but the latest upstream WorldEdit & WorldGuard ones, (i.e. areashop-worldedit-7_beta_4), and remove the FAWE hook integration here.

https://github.com/NLthijs48/AreaShop/blob/e0bad7397c18e460f3d298b76d3a128254ce54ce/AreaShop/src/main/java/me/wiefferink/areashop/AreaShop.java#L266

Doing so will make AreaShops compatible with FAWE 1.13 since FAWE 1.13 should be pretty much compatible with upstream WorldEdit now to begin with. At least from my testing.

**Comment by mrcoffee1026** [comment]
As I said this happened on every available version (I did not include logs from every available version).  But thanks for finding that the issue is areashops.  But this is a no go until that plugin functions too.  Thanks again, I'll keep an eye on fawe and theirs until they're working together again.

**Comment by mrcoffee1026** [comment]
Your downloads give the same results so you must be making changes to the .plugin.yml in the jar to make this issue go away is my guess.   This change should be merged or something in order for this to go away.  I've tried both spigot and paper and am getting the same error on startup.  Also tried the last build of worldguard that was put about 13 hours ago as well as the beta3 build.

**Comment by mrcoffee1026** [comment]
I caught this link in the discord at some point basically stating its the only that one that will work with an up to date worldguard (https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/)  and the link provided above doesn't work anymore either.  The correct Jenkins server to use for FAWE does seem to be quite the moving target.  I'm not sure what the link you gave here for FAWE goes to, I had been using it for a time too, but it's been stuck on failed builds for awhile now... even if the builds hadn't failed, every version I'd tried had provided the error here for me so I'm not sure under what conditions it actually does work, but it's really not obvious how to come across that set of circumstances.  The "breaking" builds fix it for me, however.
